### ISSUE TITLE
pricing.js - Uncaught TypeError

### ISSUE THREAD

**Issue by steveush** [Freemius/wordpress-sdk#101]
Hi guys,

When viewing the Pricing page in the WP admin there is an unhandled exception being thrown. On line 43 of the pricing.js file you're calling `priceLabel.indexOf('/')` but the `priceLabel` variable is `undefined`.

This error is repeated when toggling between the licenses for a product as well.

![freemius-pricing-error](https://cloud.githubusercontent.com/assets/1692151/19723148/41a381d2-9b7a-11e6-9c69-6a73e4444a3d.jpg)

Thanks

**Comment by vovafeldman** [comment]
Sorry about that - fixed earlier today.
