### ISSUE TITLE
Allow users which have not opted in the ability to start a trial

### ISSUE THREAD

**Issue by Vernal** [Freemius/wordpress-sdk#107]
Our flow is such that we do not necessarily want to require .org users opt in to use the free version of our service. We do, however, want to market a 30 day free trial (we collect the card up front) to the same group of users.

Currently, if a user did not opt in upon activation, they can upgrade, but they cannot take advantage of a trial.

**Comment by bradvin** [comment]
@vovafeldman we have a similar situation, and would really like the ability to offer NON-opted in users the ability to trial the PRO version. 

Sometimes, only after using the free version of the plugin, do users want to start a trial to see what PRO features are available.

If there is a setting that we can set on the freemius dashboard for offering trials to "opted in users", "non-opted in users", or "both", that would be very handy and would allow the plugin author to choose which way he wants to use the feature.

We have found that almost 23% of trial users convert and buy the PRO version. So we really need more users to try the trial version. Non opted in users have no idea about a trial version, so we are potentially loosing out on a lot of sales. (currently 55% of our users do not opt-in!).

If this is implemented, then when a user who has not previously opted in decides to try out the trial, show the opt-in dialog again, as a trial requires an opt-in. This will also increase opt-ins hopefully.

**Comment by awarner20** [comment]
This should also not matter whether Trials are requiring payment info or not.

**Comment by vovafeldman** [comment]
We understand the value of trials and will make it happen.

@awarner20, @bradvin, @Vernal - would you allow a trial to userX on site2 if the same user already utilized a trial of the same product on site1?

**Comment by Vernal** [comment]
Awesome. I am totally fine with trials based on URL rather than user. Yes
please.

**Comment by Vernal** [comment]
Hey @vovafeldman any word on how long it may be until this is ready? Just a ballpark would be handy.

J

**Comment by bradvin** [comment]
hey @vovafeldman - I think this should be configurable by the plugin author in the Freemius dashboard to allow userX a trial on 2 different sites. A freelancer who uses the same admin email to login to 2 different client sites could start a trail on their behalf on the 2 different sites

**Comment by bradvin** [comment]
and thanks for building this in! We really appreciate your hard work and commitment @vovafeldman

**Comment by vovafeldman** [comment]
@bradvin first release will restrict the trial based on the site's `home_url()`. Later we might add an option to restrict it per user email.
