### ISSUE TITLE
Cannot get freemius to display in the currently selected language 

### ISSUE THREAD

**Issue by mikesmth** [Freemius/wordpress-sdk#109]
I added a translation file for ru_RU, after which the strings still display in English. 
With the built in function __() translation takes place. However, it seems that it's not working with the __fs() function. I'm confused... 
<img width="788" alt="screen shot 2016-11-16 at 13 29 35" src="https://cloud.githubusercontent.com/assets/2362821/20343908/5e01fb0a-ac01-11e6-91bf-cad2c5abe458.png">
Anyone any idea what's happening here? Whenever this works, I'll be happy to share the Russian and Dutch translations ;-)

**Comment by vovafeldman** [comment]
Hi Mike, where did you add the translation file/s to? What filenames did you use?

By default, Freemius using its own text domain - 'freemius', and the translation files are loaded from a folder within the SDK. 

Also, it would be great if you can join our translators community and translate it there so everyone can enjoy the fruits of your labor:
https://www.transifex.com/freemius/wordpress-sdk/

**Comment by mikesmth** [comment]
Hey Vova,
Strangely enough after instelling another instance of wordpress, all is well!
I will join in on translation when we're done translating, so you'll have em complete. 
Anyone can join us with that here for now:
http://mybesttools.endofinternet.org:8088

**Comment by vovafeldman** [comment]
@mikesmth just sent you an invite to Russian and Dutch. Thanks for your contribution!
