### ISSUE TITLE
Increase Feature Title length or make html exempt? 

### ISSUE THREAD

**Issue by Vernal** [Freemius/wordpress-sdk#110]
The allowable length of feature titles could be increased a bit perhaps? Or, alternatively, do not have html elements count toward the character count? We'd like to include a link in one of our feature titles but that then leaves almost no room for text.

![screen shot 2016-11-16 at 9 59 14 am](https://cloud.githubusercontent.com/assets/80932/20351971/6ba119bc-abe3-11e6-9a5e-abdd6f22f440.png)
![screen shot 2016-11-16 at 9 59 23 am](https://cloud.githubusercontent.com/assets/80932/20351965/66b191de-abe3-11e6-9e69-f991228c1af6.png)

**Comment by vovafeldman** [comment]
Nice! Didn't know we support HTML there :) We won't be able to increase that with our current backend relational storage since the feature description column is limited in the DB level and if we increase that it will inflate the whole size of that table.

**Comment by Vernal** [comment]
Ok gotcha. Thanks for looking!
