### ISSUE TITLE
Multi-site License Activations

### ISSUE THREAD

**Issue by bradvin** [Freemius/wordpress-sdk#111]
How does a multi-site license customer activate his license key on a new website?

Do they need to opt-in again on a new domain, and then enter a license key?

Workflow example:
1) User downloads plugin on site A, opts-in and upgrades to PRO and purchases multi-site license key.
2) User installs PRO version on site B, and decides NOT to opt-in. 

How can the user activate their license key on site B?

**Comment by bradvin** [comment]
I found an "Activate License" on the plugins listing page:

![image](https://cloud.githubusercontent.com/assets/1409490/20361210/6b1f7eb4-ac3f-11e6-8f34-693f08909d93.png)

I then deleted all my accounts from the freemius debug page, but the problem I have now is that the "Activate License" link is done

**Comment by vovafeldman** [comment]
What do you mean the link is "done"?

**Comment by bradvin** [comment]
edited - should have be "gone"

**Comment by gfirem** [comment]
How this should work?

**Comment by bradvin** [comment]
I do not mean on a multisite WP install, but rather a license for multiple sites. (or a license with a site quota of > 1)
Sorry I should have been more careful with my choice of wording.

**Comment by gfirem** [comment]
Ok, thanks @bradvin, good to know multiples site. Iam looking a solution for multi-site.

**Comment by vovafeldman** [comment]
Developed a while ago with the multi-site network integration.
