### ISSUE TITLE
Change Plan Option - Your Plan .vs Upgrade Plan

### ISSUE THREAD

**Issue by awarner20** [Freemius/wordpress-sdk#112]
When upgrading a plan and you go to the pricing page, it initially shows as "Your Plan", with your current plan selected. When changing to a new plan this text does not change to Upgrade Now or something along those lines.

**Comment by vovafeldman** [comment]
I'm not exactly sure which text do you refer. Can you add a screenshot?

**Comment by awarner20** [comment]
Example:

This is a single domain license. If I want to upgrade to a 5 domain license, when I select that it would be a better user experience to have the button text change from "Your Plan" to "Upgrade Now".

<img width="366" alt="screen shot 2016-11-17 at 6 44 01 am" src="https://cloud.githubusercontent.com/assets/485517/20388136/8b667a04-ac91-11e6-84dc-90b377c99030.png">

**Comment by vovafeldman** [comment]
Understood 👍
