### ISSUE TITLE
Remove incorrect 1.7.3 and 1.7.4 tags?

### ISSUE THREAD

**Issue by cyberhobo** [Freemius/wordpress-sdk#115]
These tags look to packagist and composer (and any other automated release consumer) like the most recent versions.

**Comment by vovafeldman** [comment]
Tags renamed to the correct versions `1.1.7.3` and `1.1.7.4`.

For reference, those are the commands making it happen:
```
git tag new old
git tag -d old
git push origin :refs/tags/old
git push --tags
```

**Comment by cyberhobo** [comment]
thanks!
