### ISSUE TITLE
The upgrade link does not allow for trials

### ISSUE THREAD

**Issue by Vernal** [Freemius/wordpress-sdk#117]
Hey Guys,

If a site is eligible for a trial the Upgrade submenu item should bring them to the trial=true version of the upgrade page. Don't you think?

Jason

**Comment by Vernal** [comment]
PS - perhaps it does, but since i've already done a trial on this site i'm not seeing the upgrade language? I am in sandbox mode, though.....

**Comment by vovafeldman** [comment]
It does, but only during the trial promotion, which means 24 hours after installation until the user dismiss the trial notice.

The we don't want to make that the default link is because it will reduce conversion, since if a user want to upgrade, he'll have to go through a trial.

**Comment by Vernal** [comment]
Cool man. Let's play with this sometime this weekend.
