### ISSUE TITLE
Undefined property: stdClass::$path

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#119]
To replicate:
1. Activate a premium version and activate the license
2. Deactivate the premium version
3. Activate the lite version, the error appears. (if it doesn't appear, go to `wp-admin/plugins.php`)
* Also works if you go through the normal upgrading process (download lite -> activate license -> deactivate lite -> activate premium -> undefined property error)

This warning shows once then disappears after a refresh.
![screen-shot-2016-12-03-at-10 24 03-am](https://cloud.githubusercontent.com/assets/1033611/20856172/c2855bfe-b943-11e6-9e10-465c540af19d.jpg)

Possible fix at line `583` at class-freemius.php:

	// Try to load the cached value of the file path.
	if ( isset( $this->_storage->plugin_main_file ) ) {
		if ( property_exists( $this->_storage->plugin_main_file, 'path' ) ) {
			if ( file_exists( $this->_storage->plugin_main_file->path ) ) {
				return $this->_storage->plugin_main_file->path;
			}
		}
	}

**Comment by vovafeldman** [comment]
Fixed at #129, will be officially released in a few days (v.1.2.5)
