### ISSUE TITLE
Email unsubscribe not working

### ISSUE THREAD

**Issue by arielk** [Freemius/wordpress-sdk#12]
Hi !
When I press in unsubscribe button I moved to this link: `https://api.freemius.com/account/unsubscribe/?s_id=XXXXX&s_secure=XXXXXXX&s_ts=XXXXX&s_type=X`, 

and I get this error:

`{"path":":","error":{"type":"","message":"You must provide the Api's version in the request path. Example: \/v1\/developers\/3\/plugins\/4\/installs.json","code":"missing_version","http":400,"timestamp":"Mon, 14 Dec 2015 17:04:03 +0000"}}`

**Comment by dgwyer** [comment]
@fajardoleo Is this still an issue anymore do you think? Seeing as it was initially reported so long ago it's probably fixed by now?
