### ISSUE TITLE
Fatal PHP error: __clone method called on non-object

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#120]
`__clone method called on non-object in /srv/www/wordpress-default/wp-content/plugins/page-builder-sandwich-core/freemius/includes/class-freemius.php on line 6230`

So far, I cannot replicate this, but I've gotten reports of this.

Line in question is:

```
$this->_user = clone $users[ $this->_site->user_id ];
```

I was given a dump on both of those, `$this->_site->user_id` is:

`150213`

and `$users` as:

```array
 215356 =>
   object(FS_User)[2626]
     public 'email' => string 'something@something.com' (length=17)
     public 'first' => string '...' (length=6)
     public 'last' => string '...' (length=4)
     public 'is_verified' => boolean true
     public 'customer_id' => null
     public 'gross' => int 0
     public 'public_key' => string '...' (length=32)
     public 'secret_key' => string '...' (length=32)
     public 'id' => string '215356' (length=6)
     public 'updated' => string '2016-11-14 08:13:55' (length=19)
     public 'created' => string '2016-11-14 08:13:54' (length=19)
     private '_is_updated' (FS_Entity) => boolean false
```

I think the case should just be handled when the user id isn't found in the array.

**Comment by vovafeldman** [comment]
We want to solve the problem correctly which first requires understanding why is it happening. Just patching things isn't the solution.

Same as with the previous ticket, please provide more details and try getting the WP Admin + FTP so we can check it out.

**Comment by bfintal** [comment]
@vovafeldman I would love to provide it. However, we cannot pinpoint why it's happening, and it's hard to ask the customers about this because from what I can gather, people encounter it while in the process of activating the plugin

**Comment by vovafeldman** [comment]
Here's what I recommend, this licensing issue became a pain in the bot and the thing is that we couldn't manage to reproduce it, so temporary add me with [v AT Freemius DOT com] to your Help Scout, and assign the license related issues directly to me. That way we won't have this "middle man" situation and I will get everything I need from the customers and hopefully resolve this edge case asap.

**Comment by bradvin** [comment]
@vovafeldman did you find the cause for this? I currently have a customer who is getting this fatal error. At the very least, is there a way to clean the freemius cache, because at the moment there is no access to the wp-admin at all. My recommendation to the customer was to delete the plugin completely so that they can at least login to their site again

**Comment by bradvin** [comment]
Is there a Freemius cache clear plugin that I can install and clear any Freemius settings? Similar to the "Delete All" button on the ?page=freemius page

**Comment by vovafeldman** [comment]
Merging this ticket with https://github.com/Freemius/wordpress-sdk/issues/170
