### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#121]
I've gotten emails from customers specifying this error upon license key activation: `Warning: Invalid argument supplied for foreach() in /srv/www/user/htdocs/web/app/plugins/my_plugin/freemius/includes/class-freemius.php on line 5205`

Line that errors out is:

    foreach ( $this->_licenses as $license ) {

This occurs when you activate a license (may have something to do with EDD migration, unsure). `$this->_licenses` is `0`

<img width="882" alt="screen shot 2016-11-23 at 7 10 41 pm 1" src="https://cloud.githubusercontent.com/assets/1033611/20856613/1a695604-b94e-11e6-8322-112f13d55496.png">

Possible fix:

		function _get_license_by_id( $id ) {
			$this->_logger->entrance();

			if ( ! is_numeric( $id ) ) {
				return false;
			}

			if ( ! $this->has_any_license() ) {
				$this->_sync_licenses();
			}

			// Don't continue if there are no licenses found.
			if ( empty( $this->_licenses ) ) {
				return false;
			}

			foreach ( $this->_licenses as $license ) {
				if ( $id == $license->id ) {
					return $license;
				}
			}

			return false;
		}

**Comment by vovafeldman** [comment]
1. Did you make any changes that suddenly your customers started getting this?
2. Did they purchase from within the dashboard or via Checkout?
3. Can you ask for WP + FTP access to one of those customers?

**Comment by bfintal** [comment]
1. When the user experienced this, he came from a non-Freemius copy to a Freemius one.
2. They already had an EDD license key.
3. I'm currently waiting for a reply on this.

**Comment by bfintal** [comment]
Cannot get an ftp because it happened on a local dev environment. It showed up when upgrading the plugin by replacing the plugin files instead of going through the activate/deactivate process.

**Comment by vovafeldman** [comment]
When you say "replacing", what exactly do you mean? Because the premium plugin version has a different folder name. Can you please ask the user?

**Comment by vovafeldman** [comment]
Closing this ticket due to inactivity.
