### ISSUE TITLE
Fatal error: __clone method called on non-object 

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#122]
Original issue: https://wordpress.org/support/topic/fatal-error-urgent-help/#post-8513009

Fatal error: __clone method called on non-object in /DATA/p/i/r/pirouetteb_1/www/wp-content/plugins/popup-maker/includes/libs/freemius/includes/class-freemius.php on line 6169

**Comment by vovafeldman** [comment]
As a start, I need to know what SDK version this guy is running.

**Comment by danieliser** [comment]
Just asked, but assuming he is using the latest Popup Maker then it would be 1.2.1

**Comment by vovafeldman** [comment]
Closing this ticket due to inactivity.
