### ISSUE TITLE
PHP errors before header.

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#123]
Original Report: https://wordpress.org/support/topic/freemius-conflict-with-gantry-5-framework/#post-8532016

Whoops \ Exception \ ErrorException (E_WARNING) Cannot modify header information – headers already sent by (output started at /public_html/wp-content/plugins/popup-maker/includes/libs/freemius/includes/class-freemius.php:6830)

**Comment by vovafeldman** [comment]
Same here, when you open a ticket we need the SDK version to take a look.

**Comment by vovafeldman** [comment]
Old ticket, the SDK had many iterations since 2016.
