### ISSUE TITLE
Activation email contains wrong instructions if trialing without account

### ISSUE THREAD

**Issue by Vernal** [Freemius/wordpress-sdk#124]
I've been playing with #107 and found a problem in the logic.

If a user has not activated/opted-in and starts a trial, an email is sent to them asking them to activate, download, upload, etc. It looks like this:
![screen shot 2016-12-08 at 10 59 23 pm](https://cloud.githubusercontent.com/assets/80932/21037412/8a830b0a-bd9b-11e6-9de5-7b89cf253718.png)

The problem is that in our edge case we do not have a premium version of our plugin. There is only one version. It is free, and in the repo. Buying service just activates our api.

**Comment by vovafeldman** [comment]
@Vernal how will the process look like if the user wants to purchase directly from your site? Ping me on Slack when you have a few minutes.

**Comment by Vernal** [comment]
Again, we are an edge case - in which our plugin will always be in the repo. In our case we aren’t using any of the freemius deploy tools. Maybe that’s something the email template could take notice of and not offer a download link?

I’m on slack all day...

**Comment by Vernal** [comment]
Wahohooooo!
