### ISSUE TITLE
Cannot extend Freemius class because of private visibility

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#126]
I'm trying to modify how it's doing things without touching the actual SDK and retaining everything else to be the same. I'm extending the `Freemius` class instead of creating my own class from the abstract `FreemiusAbstract` class to that I can just do small changes. I've extend the `Freemius` class to like this:

	class FreemiusMod extends Freemius {
		function can_use_premium_code() {
			return true;
		}
	}

..but I cannot create an instance because the `__construct()` is private and I cannot call it. So I tried including the `instance` function also.

	class FreemiusMod extends Freemius {
		function can_use_premium_code() {
			return true;
		}
		static function instance( $slug, $is_init = false ) {
		   $slug = strtolower( $slug );

		   if ( ! isset( self::$_instances[ $slug ] ) ) {
			   if ( 0 === count( self::$_instances ) ) {
				   self::_load_required_static();
			   }

			   self::$_instances[ $slug ] = new FreemiusMod( $slug, $is_init );
		   }

		   return self::$_instances[ $slug ];
	   }
	}

That wouldn't work either because `self::$_instances` and `_load_required_static()` were also private.

Would it be possible to make some of the private functions/properties `protected` instead of `private`?

**Comment by vovafeldman** [comment]
@bfintal what you want to extend is `Freemius_Abstract`, not `Freemius`. Or do I miss something?

**Comment by bfintal** [comment]
@vovafeldman my goal was to override the `can_use_premium_code()` function only. The rest of the class' behavior would be the same, that's why I extended from `Freemius` instead of `Freemius_Abstract`

**Comment by vovafeldman** [comment]
I think you can implement it with PHP "magic" access. Each `FreemiusMod` should hold an instance of `Freemius` and when a property/method of `FreemiusMod` is accessed/called, if it's not part of `FreemiusMod` you can delegate it to the `Freemius` instance.

**Comment by bfintal** [comment]
Good idea, I didn't think of that. It works, although there's a ton of code to make it work:

	class FreemiusEnvato extends Freemius_Abstract {

		protected $freemius_instance;
		protected static $_instances = array();

		function __construct( $slug, $is_init ) {
			$this->freemius_instance = Freemius::instance( $slug, $is_init );
		}

		/**
		 * Check if user is a trial or have feature enabled license. Always true for Envato.
		 *
		 * @return bool
		 */
		function can_use_premium_code() {
			return true;
		}

		/**
		 * Main singleton instance.
		 *
		 * @param string $slug Instance slug.
		 * @param bool   $is_init Is initiation sequence.
		 *
		 * @return Freemius
		 */
		static function instance( $slug, $is_init = false ) {
			$slug = strtolower( $slug );

			if ( ! isset( self::$_instances[ $slug ] ) ) {
				self::$_instances[ $slug ] = new FreemiusEnvato( $slug, $is_init );
			}

			return self::$_instances[ $slug ];
		}

		public function __call( $name, $arguments ) {
			if ( ! method_exists( $this, $name ) ) {
				return call_user_func_array( array( $this->freemius_instance, $name ), $arguments );
			}
		}

		public function is_registered() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_anonymous() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_activation_mode( $and_on = true ) {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_org_repo_compliant() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_paying() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_trial() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_trial_utilized() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_free_plan() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_plan( $plan, $exact = false ) {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_trial_plan( $plan, $exact = false ) {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function has_paid_plan() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function has_free_plan() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_only_premium() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_payments_sandbox() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_live() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_premium() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function get_upgrade_url( $period = WP_FS__PERIOD_ANNUALLY, $is_trial = false ) {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_plugin_new_install() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function has_purchased_before() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_agency() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_developer() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}

		public function is_business() {
			return $this->__call( __FUNCTION__, func_get_args() );
		}
	}

**Comment by vovafeldman** [comment]
Why do you need to configure all the methods that you don't need to override? Isn't that what `__call` for?

**Comment by bfintal** [comment]
It still errors out even with `__call()` and says that the abstracted methods need to be added. :(

**Comment by vovafeldman** [comment]
With the magic approach, your class neesd to extend `Freemius`, that way you don't need to implement any of the abstract methods.

**Comment by bfintal** [comment]
I cannot extend the `Freemius` class, doing that will pull us back to the original problem with private function visibility.

**Comment by vovafeldman** [comment]
@bfintal I don't understand why it will trigger visibility issues. It's a simple delegation to the `Freemius` class, besides the override of the `can_use_premium_code()` method. Ping me on slack when you have a moment.

**Comment by bfintal** [comment]
Let me take a stab at explaining this again.

I'm trying to override the `can_use_premium_code()` function while retaining all the other behavior for a specific build I have.

Normally, to initialize the SDK, I'd need to use this function:

	function fs_dynamic_init( $module ) {
		$fs = Freemius::instance( $module['slug'], true );
		$fs->dynamic_init( $module );
		return $fs;
	}

My thinking is that I can use a modified `Freemius` class by extending that class, changing the output of its `can_use_premium_code` and then performing the stuff called by `fs_dynamic_init`. (Yes it got complicated, but if there's an easier way, let me know)

If I do this and assuming that I don't have a license active:

	class FreemiusMod extends Freemius {
		function can_use_premium_code() {
			return true;
		}
	}

	// Note that $module was defined earlier.
	$pbs_fs = FreemiusMod::instance( $module['slug'], true );
	$pbs_fs->dynamic_init( $module );
	
	var_dump( $pbs_fs->can_use_premium_code() ); // This prints "false"

This outputs `false` and not `true` because the inherited `FreemiusMod::instance` returns a `Freemius` object, so my `FreemiusMod` isn't used at all. So maybe to fix it I could initialize it right away:

    new FreemiusMod( $module['slug'], true );

But I can't because the constructor is private:

    Fatal error: Call to private Freemius::__construct() from invalid context

So in order for this to work, I'd also need to override the `instance` function:

	static function instance( $slug, $is_init = false ) {
	   $slug = strtolower( $slug );

	   if ( ! isset( self::$_instances[ $slug ] ) ) {
		   if ( 0 === count( self::$_instances ) ) {
			   self::_load_required_static();
		   }

		   // Changed line.
		   self::$_instances[ $slug ] = new FreemiusMod( $slug, $is_init );
	   }

	   return self::$_instances[ $slug ];
	}

This gives out the error:

    Fatal error: Cannot access property FreemiusMod::$_instances

To address that error, I can instead create my own `$_instances` property since I'm the only one who'll use this special class anyway:

    private static $_instances = array();

Now the error becomes:

    Fatal error: Call to private method Freemius::_load_required_static() from context 'FreemiusMod' 

I cannot continue anymore since re-defining `_load_required_static` would lead to more of those Call to private method/property errors and if I continue, I'd end up with a clone of the `Freemius` class.

While the super long code I pasted above works (the one with all the abstract functions defined), the problem is that I would need to keep track of newly defined functions when updating the SDK, or else I would get errors from undeclared functions.
