### ISSUE TITLE
Hmm... notice is added after upgrade message

### ISSUE THREAD

**Issue by cyberhobo** [Freemius/wordpress-sdk#128]
Seeing this on the `develop` branch when testing the upgrade flow:

<img width="1268" alt="screenshot 2016-12-12 15 55 41" src="https://cloud.githubusercontent.com/assets/286838/21121943/18ab1842-c084-11e6-9ee6-0684d27b3de9.png">

It stays if refreshed, but disappears when another admin page is loaded.

**Comment by cyberhobo** [comment]
Actually that screenshot was using the 1.2.1 release, but I believe I've seen this on the `develop` branch also.

**Comment by vovafeldman** [comment]
@cyberhobo the message with the **x Dismiss** button is sticky, which means that it will stay until the user will click it.

The 2nd message appears because you refresh the page while it has special params that direct the SDK to re-sync the license from the API. If you just open the Account page, it won't show up.

Or am I missing something?

**Comment by cyberhobo** [comment]
I think this is a side effect of my attempt to use the same plugin for both free and premium plans, with no extra download. I think I'll close this, experiment a bit more, and start a new issue on that topic with more background.

**Comment by Vernal** [comment]
Hey @vovafeldman we are starting to see this one in the wild. One of our beta testers experienced it today. Thoughts?
![slack_-_vernal](https://cloud.githubusercontent.com/assets/80932/21897237/fdd409d4-d8b6-11e6-8789-c2be52d74910.png)

**Comment by vovafeldman** [comment]
My guess is that there's a plugin/theme with a newer SDK version running on this site. Please ask the user to send a screenshot from `/wp-admin/admin.php?page=freemius`.

**Comment by Vernal** [comment]
Ok. A second tester (me!) just got it. Here it is. I do have full access to this site if you want me to poke anything.
<img width="1204" alt="_melville_charitable_trust_ _wordpress" src="https://cloud.githubusercontent.com/assets/80932/21916319/c7efe9b2-d90d-11e6-8c58-00f33193367a.png">

**Comment by Vernal** [comment]
PS - I control the plugins on this site and nothing else on there uses Freemius...

**Comment by Vernal** [comment]
Ok and here is one more for science.
<img width="1111" alt="postmaticscreenshot_jpg" src="https://cloud.githubusercontent.com/assets/80932/21916907/91e50128-d911-11e6-9c3a-477b5c11dfe4.png">

**Comment by vovafeldman** [comment]
For the latest screenshot, try changing the version var to `1.2.1.6` in `freemius/start.php` to make sure that your SDK will be loaded (and we'll release those changes with `1.2.1.6` anyway).

**Comment by cyberhobo** [comment]
Would it make sense to change that version in the develop branch?

**Comment by vovafeldman** [comment]
@cyberhobo version updated in `develop`.

**Comment by cyberhobo** [comment]
Thanks Vova!
