### ISSUE TITLE
VAT ID missing from receipts

### ISSUE THREAD

**Issue by sebet** [Freemius/wordpress-sdk#13]
After a couple of tests using a VAT ID it looks like that information is not included in any of the receipts sent to the author and customers.

I'm attaching some screens with the VAT ID placed during checkout and the receipts I've received

Am I missing something?

**Checkout**
![checkout with vat id](https://cloud.githubusercontent.com/assets/1154179/11903814/a9f8fe32-a5b3-11e5-9950-957e341aa012.png)

**Customer Receipt**
![customer-receipt](https://cloud.githubusercontent.com/assets/1154179/11903816/a9fb1dc0-a5b3-11e5-8138-6ac53a5cb90e.png)

**Payment Received Receipt**
![payment received -receipt](https://cloud.githubusercontent.com/assets/1154179/11903864/2a423248-a5b4-11e5-90fd-5f03e19aeb31.png)

.

**Comment by vovafeldman** [comment]
Hey @sebet, thanks for finding the glitch. It should be good now - the emails will contain the VAT ID if provided by the user. Could you please verify on your side?

**Comment by sebet** [comment]
Thanks for the fix @vovafeldman. I'll check and inform you if the issue persists.

**Comment by vovafeldman** [comment]
I'm closing the issue. You can re-open it if you still find VAT problems.
