### ISSUE TITLE
Upgrade with no download required

### ISSUE THREAD

**Issue by cyberhobo** [Freemius/wordpress-sdk#130]
I'm working on two plugins with slightly different use cases:

1. I offer only one paid plan that only adds priority email support on upgrade (Geo Mashup)
2. A serviceware plugin only adds service features on upgrade (Replyable)

In both cases an upgrade shouldn't require a new plugin to be downloaded and installed.

Vova suggested an approach on slack:

![screen shot 2016-11-22 at 8 24 08 am](https://cloud.githubusercontent.com/assets/286838/20532400/b455a0b0-b08e-11e6-9993-b301928b37a6.png)

I've implemented that in both cases. I think it can work but will require some adjustments. 

The first I noticed is that we need to switch `is_premium` back to false on the `after_account_delete` hook. I've implemented that too. I think we also need a hook to do this on license deactivation.

Let's look at how this affects a common upgrade flow:

1. Freemius is connected, data collection is allowed and email verified.
2. Click the upgrade link.
3. Click "upgrade now" on a paid plan, enter payment info (sandbox prefill in my case).
4. Click "Review Order".
5. Click "Pay and Subscribe".

Here we get two notices. The first is a sticky "Yee-haw!..." notice with download instructions, the one we were trying to avoid. I think this is because we've changed our local `is_premium` option value on the `after_license_change` hook, but Freemius was still initialized with `is_premium` set to `false`. The second notice is the non-sticky "Hmm... It looks like you are still on the Business plan. If you did upgrade or change your plan, it's probably an issue on our side - sorry. Please contact us here". This is due to the query parameter `fs_action=<slug>_sync_license` - we need to find a way to prevent that.

If I now refresh the page without changing the URL, the first notice changes to "W00t! Premium plugin version was successfully activated.", because Freemius is initialized with `is_premium` set to `true` this time. 

How should we address these two problems with this flow? A redirect to a clean URL in our `after_license_change` hook might do the trick, but I don't want to prevent any additional Freemius processing.

**Comment by Vernal** [comment]
Thanks, @cyberhobo. This is closely related to other non-premium workflow issues we are looking at with #124. Just tagging that here.

**Comment by vovafeldman** [comment]
Already as part of the `develop` branch, will be released with the next version.
