### ISSUE TITLE
Upgrade screen: VAT not included in discounted price

### ISSUE THREAD

**Issue by intoxstudio** [Freemius/wordpress-sdk#131]
**Actual Behavior**:
 -  `What is the issue?`
When purchasing plugin from the Upgrade admin screen and applying a coupon code, the "Today's total" does not include VAT:
<img width="584" alt="udklip" src="https://cloud.githubusercontent.com/assets/1677777/21580433/f2f3986a-cff4-11e6-845c-3c2912c2cb62.PNG">

 -  `What is the expected behavior?`
Correct price should be $199, correct discount should be $49.75. Danish VAT is 25%.
**Works as expected in Checkout**, except also displaying incorrect discount of $39.80 to the user.

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1
 -  `WordPress Version:` 4.7
 -  `PHP Version:` 7

**Plugin / Theme**: (*)
 -  `Name:` Content Aware Sidebars
 -  `Slug:` content-aware-sidebars
 -  `Freemius ID:` 259

**Additional Information**:
 -  `Browser Type: (*)` Chrome
 -  `Browser Version: (*)` 55
 -  `OS: (*)`Win10
 -  `Stack Traces:`

**Comment by vovafeldman** [comment]
We are deprecating the current in-dashboard checkout with the new checkout we use for Freemius Checkout. It will help us to be more agile when it comes to changes and maintenance (only one code base). Plus, the new checkout is written in angular which makes it more sustainable for the long run. So I'm closing this task. If it happens also in Freemius Checkout, please re-open.
