### ISSUE TITLE
Install an addon of a plugin but result to activate

### ISSUE THREAD

**Issue by Mte90** [Freemius/wordpress-sdk#132]
**Actual Behavior**:
 -  `What is the issue? (*)`
Install/update an addon of the plugin sell on freemius, on the account page with the licenses key on the addons section I get a button to activate that redirect the plugin list with the plugin as activated (but was already active). When I go to the account page is like before and not show the license with the button to active the plugin.
 -  If the addon of the plugin is active show the license key

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1.5
 -  `WordPress Version:` 4.7

**Comment by vovafeldman** [comment]
Can you please attach a screenshot of the button you are talking about?

**Comment by vovafeldman** [comment]
Did you just install the add-on? Or did you purchased it from within the dashboard first?

**Comment by Mte90** [comment]
It's a customer so he buy it but I am not sure about the procedure but in any case the plugin is active only that in this dashboard result not activated.

**Comment by vovafeldman** [comment]
@Mte90 please contact me via _support AT freemius DOT com_ with a temporary WP admin access to the site and we'll investigate.
