### ISSUE TITLE
404s on PNG and JPG images instead of using SVG from WordPress.org

### ISSUE THREAD

**Issue by cliffordp** [Freemius/wordpress-sdk#135]
**Actual Behavior**:
 -  `What is the issue? (*)`

404s for these images:
- https://cl.ly/231C0E1J1W2n at Contact Us
- https://cl.ly/1V0L0t34231F at checkout

https://wordpress.org/plugins/tk-event-weather/ --> https://plugins.trac.wordpress.org/browser/tk-event-weather/assets only has icon.svg, no PNG or JPG, which is compliant with .org

I noticed these 404s during checkout.

 -  `What is the expected behavior?`
If SVG exists, just use that.

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1.5
 -  `WordPress Version:` 4.7
 -  `PHP Version:` 5.5.24

**Plugin / Theme**: (*)
 -  `Name:` TK Event Weather
 -  `Slug:` tk-event-weather
 -  `Freemius ID:` 240

**Additional Information**:
 -  `Browser Type: (*)` Chrome
 -  `Browser Version: (*)` 54.0.2840.98
 -  `OS: (*)` OS X Sierra 10.12.2
 -  `Stack Traces:` N/A

**Comment by vovafeldman** [comment]
WordPress.org plugin icons can have different extensions, we were using an HTML hack to let the browser try load all the extensions, and only show the valid one.

But we recently added a mechanism that pulls plugin icons from the .org plugins API to also show them in the developer's dashboard, so we updated the code that renders the HTML image and you shouldn't see any errors now.
