### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by gfirem** [Freemius/wordpress-sdk#140]
Hi, will be awesome some solution to use into the network in a multisite installation. Maybe detect the license key have a unlimited sites and dont show the opt-in in the child sites.

**Comment by bfintal** [comment]
+1

**Comment by vovafeldman** [comment]
Multi-site network integration was introduced at [v.2.0.1](https://github.com/Freemius/wordpress-sdk/releases/tag/2.0.1)
