### ISSUE TITLE
Allow coupons to be applied to a specific plan and bulk option only

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#142]
We have a requirement right now to produce a coupon that would only apply for a specific license/bulk option only.

I suggest to add 2 dropdowns to the coupon to select a **plan** and a **license #**, similar to the dropdowns shown when you manually create a license:

<img width="1077" alt="screen shot 2017-02-08 at 12 23 12 am" src="https://cloud.githubusercontent.com/assets/1033611/22700211/cfab59b6-ed94-11e6-9b7d-d2c1e7f33822.png">

**Comment by vovafeldman** [comment]
@bfintal this is finally in progress.

**Comment by bfintal** [comment]
@vovafeldman That is great news!

**Comment by vovafeldman** [comment]
Advanced coupons are up! Not only that you can set a coupon for specific license sites limits, you can also specify which billing cycles are supported:
![image](https://user-images.githubusercontent.com/6830121/29762414-0e618302-8bd7-11e7-8f57-ce627dbfb4a7.png)

For example, if you want to run a promotion for your 5-site lifetime plan, you can now easily do it! 

The credit here goes to @fajardoleo :+1:
