### ISSUE TITLE
[feature-request] Allow users to upgrade to a higher plan

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#147]
Right now what we're doing is we're refunding people in the lower tier bulk plan then they purchase the higher bulk plan.

My request is to allow people to:

- Upgrade from a lower bulk plan to a higher bulk plan by paying the difference, and
- Upgrade from a lower plan to higher plan by paying the difference

Expected results after upgrading:

- The existing license key would still work but now it's for the new plan / bulk plan
- The expiration of the plan would extend

**Comment by vovafeldman** [comment]
Changing plans (with proration) is already supported.
