### ISSUE TITLE
Warning: getmypid() has been disabled for security reasons

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#152]
**Actual Behavior**:
 -  User gets this at the top of admin pages.

(Warning: getmypid() has been disabled for security reasons in /www/wp-content/plugins/popup-maker/includes/pum-sdk/freemius/includes/class-fs-logger.php on line 91)

**Versions**: (*)
 -  Latest
 -  Latest
 -  Unknown

**Comment by vovafeldman** [comment]
Interesting... didn't know it's possible to disable PHP core methods 👍  I did some reading and it seems like some shared hosting are blocking it. We'll release a minor version that fixes this one. Thanks!

**Comment by danieliser** [comment]
Ty sir. Yea never seen this one either. EVER.
