### ISSUE TITLE
Missing Sanitization in class-freemius.php

### ISSUE THREAD

**Issue by Ipstenu** [Freemius/wordpress-sdk#154]
This is a bug report. The following two lines of code aren't properly sanitizing input.

https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L5989
https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L5866

`$email_address = trim( $_POST['email'] );` isn't actually sanitizing anything. You should use `sanitize_email()`

Similarly this is not sanitized: `$slug      = $_POST['slug'];`

It's incredibly hard to do anything with it, but as we all know, trust no POST data 💃

**Comment by vovafeldman** [comment]
Thanks for the note @Ipstenu - we'll fix those in the upcoming release.
