### ISSUE TITLE
Warning: get_current_user() has been disabled for security reasons

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#158]
In the admin user is getting:

Warning: get_current_user() has been disabled for security reasons in /home/bh61420/public_html/wp-content/plugins/popup-maker/includes/pum-sdk/freemius/includes/class-fs-logger.php on line 88

Not sure if you mean to use wp_get_current_user() as some hosts disable PHP get_current_user it seems.

**Comment by vovafeldman** [comment]
Thanks for reporting, we use this method to Auto populate the user's info. Any idea what is the host that blocks it?

I guess we'll create our own method with a similar logic to workaround that error.

**Comment by vovafeldman** [comment]
I did confuse it with the `wp_` one :) Can you try suggesting the user to replace that line with:
```

**Comment by danieliser** [comment]
@vovafeldman I am not sure a function_exists check here will work. In this case the error doesn't indicate the function doesn't exist, but rather that its blocked from usage.

My gut tells me it won't work this way either but I am gonna have one of the users reporting this try it to see. Will let you know shortly if they can test it and the result if so.

**Comment by ksmales23** [comment]
Did you guys get to the bottom of this issue?  I am seeing the same problem with the class-fs-logger.php  (line 88)..   It is trying to find out the server user that is running PHP, unsurprisingly this is being blocked by my host and is generating security errors.

**Comment by vovafeldman** [comment]
@ksmales23 it was resolved here 6ab44ac

**Comment by bfintal** [comment]
It seems that this issue may still be present. We just received a customer that was encountering this warning in his logs (with the latest SDK version 2.3.0):

> [18-Jul-2019 05:16:08 UTC] PHP Warning: get_current_user() has been disabled for security reasons in /home/.../freemius/includes/class-fs-logger.php on line 89
