### ISSUE TITLE
Account template headding

### ISSUE THREAD

**Issue by ramiy** [Freemius/wordpress-sdk#159]
I want to customize the freemius account template. I want to add a heading and several paragraphs above the tab-navigation. 

![freemius-account-template](https://cloud.githubusercontent.com/assets/576623/24967181/ec398aea-1fb1-11e7-8eeb-77c7fc25cc40.png)

Can you add a new WordPress action? https://github.com/Freemius/wordpress-sdk/blob/a3f3af732acbd4fe0f040e911b6cf190e0d3d4cb/templates/account.php#L43

This template already has an action at the bottom. https://github.com/Freemius/wordpress-sdk/blob/a3f3af732acbd4fe0f040e911b6cf190e0d3d4cb/templates/account.php#L710

**Comment by vovafeldman** [comment]
We already have a filter you can use for that:
```
function my_add_custom_account_html( $html ) {
    return '<h1>My title</h1>' . $html;
}

my_freemius()->add_filter( 'templates/account.php', 'my_add_custom_account_html' );
my_freemius()->add_filter( 'templates/billing.php', 'my_add_custom_account_html' );
```
