### ISSUE TITLE
PHP notices when no HTTP context.

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#16]
PHP throws notices for $_SERVER variables in API connectivity test when running without HTTP context (e.g. CLI, Cronjob). I think the best solution, in this case, would be to turn Freemius off if the user is not yet opted-in.

References:
https://wordpress.org/support/topic/errors-in-the-freemius-class-when-running-in-wordpress-in-cli

**Comment by KingYes** [comment]
:+1:
