### ISSUE TITLE
License Compatibility with GPLv3/AGPL

### ISSUE THREAD

**Issue by jhabdas** [Freemius/wordpress-sdk#166]
**Actual Behavior**:
 -  `What is the issue? (*)`
    Current licensing **restricts** SDK use in A/GPLv3-or-later projects
 -  `What is the expected behavior?`

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1.7.1
 -  `WordPress Version:` n/a
 -  `PHP Version:` n/a

**Plugin / Theme**: (*)
 -  `Name:` Hyperdrive
 -  `Slug:` hyperdrive
 -  `Freemius ID:` 1109

**Additional Information**:
 -  `Browser Type: (*)` n/a
 -  `Browser Version: (*)` n/a
 -  `OS: (*)` n/a
 -  `Stack Traces:`

Per [section 8 of the GPLv2](https://github.com/Freemius/wordpress-sdk/blob/master/LICENSE.txt#L242-L248):

> Each version is given a distinguishing version number.  If the Program
> specifies a version number of this License which applies to it and "any
> later version", you have the option of following the terms and conditions
> either of that version or of any later version published by the Free
> Software Foundation.  If the Program does not specify a version number of
> this License, you may choose any version ever published by the Free Software
> Foundation.

Because a license version is specified in this library, and _or later_ is not applied, the SDK  is not compatible for use as a lib with with GPLv3-or-later and AGPLv3-or-later projects.

The following license compatibility matrix on the GNU sums it up quite nicely:
https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

Possible directions to increase licensing compatibility for plugins and themes not using the _exact_ same version of the GPL used by this SDK include updating the SDK thusly:

- Apply GPLv2-or-later as described in section 8 copied above
- Remove the GPL version number as described in section 8 copied above
- Use GPLv3-or-later as shown in the compatibility matrix, second row heading
- Use AGPLv3-or-later as implied in the compatibility matrix (see AGPL note just before table)

**Comment by jhabdas** [comment]
@vovafeldman

**Comment by jhabdas** [comment]
@vovafeldman as a stop gap, do I have your permission to apply `GPLv2-or-later` to my copy of this software? Without application my plugin is blocked from using this SDK.

**Comment by cliffordp** [comment]
Yikes... guess I never really looked too hard, but I also have "GPLv3 or later" plugins integrating Freemius.

Good catch!

**Comment by vovafeldman** [comment]
@jhabdas based on the [wp.org guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/), __any GPL-compatible license for 3rd party libraries is acceptable__. So I'm not sure I understand what is the issue? We are actually considering to switch a license to MIT so developers will be able to use it without the restrictions of the GPL.

**Comment by jhabdas** [comment]
@vovafeldman Thanks for your note. This is not a WP concern insomuch as it is a GNU compatibility issue regardless of where hosted.

As referenced in the supporting documentation in the OP, GPLv2 is _not_ compatible with GPLv3 or later or the GNU AGPL. As a result, I look forward to seeing a compatible FOS license made available. If you're considering MIT please also consider ISC as it is the functional equivalent of MIT but with less words - making it take up less space when combined with other licenses.

**Comment by jhabdas** [comment]
@cliffordp edited my above post to add more detail and provide some useful resources. hope it helps. I did spend the better part of 3 weeks researching licenses after hitting friction with a post on the WP.org support forums, if that means anything.

**Comment by vovafeldman** [comment]
@jhabdas can you just explain me the problem in simple words. If I understand correctly, you say that GPLv2 is not compatible with GPLv3 or later, and why is that a problem for you? or anyone else?

I'm just trying to make sure I understand the issue.

**Comment by jhabdas** [comment]
@vovafeldman I cannot speak for anyone else. And I'm not a licensed attorney (that may change in a few years) but I can with confidence tell you I cannot use your library under current license in my plug-ins or themes licensed under GPLv3/AGPLv3/GPLv3-or-later/APGLv3-or-later until you apply the GPLv2 in accordance with Section 8 of the license and maintain license compatibility.

**Comment by jhabdas** [comment]
Added EDIT to the above.

**Comment by jhabdas** [comment]
Added another edit.

**Comment by vovafeldman** [comment]
@jhabdas Thanks a lot for all the details! We will have to do some reading to learn about the different licenses, potentially consult with an attorney, we can't just switch the license without understanding the implications.

**Comment by jhabdas** [comment]
@vovafeldman Whatever you gotta do. As mentioned, I'd love to be able to use this library. If you need any pointers to speed up your research see my path to enlightenment here: https://github.com/comfusion/hyperdrive/issues/41. Which lead me to [create](https://github.com/xwp/wp-dev-lib/issues/240#issuecomment-303029913) the following:

Tools/Libs (MIT/ISC) `<-` Apps ([Choose A License](https://choosealicense.com/)) `->` Plugin/Theme ("[A]GPL-[2|3].0" with `+` or `or later` or `or any
later version`, or version number omitted, depending on specific language used and as defined by the terms of the individual GNU GPL or GNU AGPL license applied).

Gotta love the GPL!

**Comment by jhabdas** [comment]
Nudge. @vovafeldman with your permission I will fork this and apply an updated license to my fork so it's compatible with GPLv3/AGPL. Please let me know. If you have legal questions you can get quick response on https://opensource.stackexchange.com and avoid the fiduciary headache.

**Comment by jhabdas** [comment]
Thanks so much for this @vovafeldman. Moving to GPL-3.0 is great as it helps others update their GPLv2 licenses to either use the _or any later version_ in their software to use the SDK, which is good as it enables then to automatically update plugins and themes to future versions of the GPL without having to think about licensing again (for the most part).

I reopened this as I noticed the _license headers_ in the `develop` branch are still showing GPL-2.0 identifiers, which you'll want to update to GPL-3.0 or GPL3.0-or-later to clean up any ambiguity.

Thank you for not becoming defensive or angry with me when I opened this issue (many do, as they seem to go through the stages of grief). Strong copyleft licenses like the GPL are some of the least sexy licenses out there, as I mention in the following article on Hacker Noon which you may find an entertaining read:

https://hackernoon.com/introducing-the-btc-license-28650887eb11

**Comment by vovafeldman** [comment]
@jhabdas updated all references to GPLv3
