### ISSUE TITLE
Error with __clone when activate 

### ISSUE THREAD

**Issue by gfirem** [Freemius/wordpress-sdk#170]
**Actual Behavior**:
 -  `What is the issue? (*)` When the user activate the plugins in his site get an error
 -  `What is the expected behavior?` The normal behavior will be activate the plugins and freemius. 

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1.7.1
 -  `WordPress Version:`4.8
 -  `PHP Version:` 5.4.45

**Plugin / Theme**: (*)
 -  `Name:` Formidable Copy Action
 -  `Slug:` formidable-copy-action
 -  `Freemius ID:`868

**Additional Information**:
 -  `Browser Type: (*)` Chrome
 -  `Browser Version: (*)`59.0.3071.115
 -  `OS: (*)` MAC
 -  `Stack Traces:` 
Fatal error: __clone method called on non-object in /home/hambel/public_html/2thepowerof1.com/wp-content/plugins/formidable-copy-action-premium/class/include/freemius/includes/class-freemius.php on line 7197

**Comment by igorbenic** [comment]
I got an email from a client stating the same. Not sure about the server configuration. I'll ask him that also and post here.

**Comment by JoseVega** [comment]
A customer of mine also reported this issue, but it´s working fine for everyone else... I don´t know have any info about the customer´s environment.

**Comment by alanef** [comment]
I have the same ( or similar ) issue

Freemius SDK Version: 1.2.3
PHP 7.0
WP 4.9.1

Uncaught Error: __clone method called on non-object in 

Going into Freemius Debug mode - cdelete accounts / clear cache fixed the issue

**Comment by vovafeldman** [comment]
The upcoming SDK comes with a recovery mechanism to avoid that edge case. I'm closing this issue for now.
