### ISSUE TITLE
[themes] [theme-check] New ThemeCheck sniffs issues

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#178]
`FILE: /freemius/includes/class-freemius.php`

### FOUND 3 ERRORS AFFECTING 3 LINES
2681 | ERROR | Silencing errors is forbidden
2682 | ERROR | Silencing errors is forbidden
8188 | ERROR | Silencing errors is forbidden

Time: 25051114 mins, 9.29 secs; Memory: 151Mb

`FILE: /freemius/includes/l10n.php`

### FOUND 21 ERRORS AFFECTING 9 LINES
  23 | ERROR | The $text arg must be a single string literal, not "$text".
  23 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
  36 | ERROR | The $text arg must be a single string literal, not "$text".
  36 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
  49 | ERROR | The $text arg must be a single string literal, not "$text".
  49 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
  60 | ERROR | The $text arg must be a single string literal, not "$text".
  60 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
  71 | ERROR | The $text arg must be a single string literal, not "$text".
  71 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
  82 | ERROR | The $text arg must be a single string literal, not "$text".
  82 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
 102 | ERROR | The $text arg must be a single string literal, not "$text".
 102 | ERROR | The $context arg must be a single string literal, not "$context".
 102 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
 130 | ERROR | The $text arg must be a single string literal, not "$text".
 130 | ERROR | The $context arg must be a single string literal, not "$context".
 130 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.
 144 | ERROR | The $text arg must be a single string literal, not "$text".
 144 | ERROR | The $context arg must be a single string literal, not "$context".
 144 | ERROR | Mismatch text domain. Expected 'best-reloaded' but got 'freemius'.

Time: 25051114 mins, 13.1 secs; Memory: 9.5Mb

`FILE: /freemius/includes/managers/class-fs-admin-menu-manager.php`

### FOUND 3 ERRORS AFFECTING 3 LINES

 571 | ERROR | Overriding WordPress globals is prohibited
 687 | ERROR | Overriding WordPress globals is prohibited
 701 | ERROR | Overriding WordPress globals is prohibited

Time: 25051114 mins, 13.32 secs; Memory: 14.75Mb

`FILE: /freemius/includes/sdk/FreemiusWordPress.php`

### FOUND 1 ERROR AFFECTING 1 LINE
 423 | ERROR | Silencing errors is forbidden

Time: 25051114 mins, 14.97 secs; Memory: 15Mb

`FILE: /freemius/templates/add-ons.php`

### FOUND 1 ERROR AFFECTING 1 LINE
 1 | ERROR | File has mixed line endings; this may cause incorrect results

Time: 25051114 mins, 16.3 secs; Memory: 9.25Mb

`FILE: /freemius/templates/debug/api-calls.php`

### FOUND 2 ERRORS AFFECTING 2 LINES
 102 | ERROR | The function json_encode() does not have a parameter "options" in PHP version 5.2 or earlier
 125 | ERROR | The function json_encode() does not have a parameter "options" in PHP version 5.2 or earlier

Time: 25051114 mins, 17.15 secs; Memory: 9.25Mb

**Comment by vovafeldman** [comment]
`FILE: /freemius/templates/debug/api-calls.php`:
Both calls will only be executed when `$pretty_print` is `true`, and if you look at the top of the file, the value is:
`$pretty_print = $show_body && defined( 'JSON_PRETTY_PRINT' ) && version_compare( phpversion(), '5.3', '>=' );`

Which means that the code will only be executed for PHP 5.3 and higher (not PHP 5.2). I will add a dummy var to work around this false positive:
```php
$encode = 'json_encode';
$encode( ... );
```

cc: @pattonwebz

**Comment by vovafeldman** [comment]
`FILE: /freemius/includes/sdk/FreemiusWordPress.php`:

This file is responsible for the API communication layer and executed after an opt-in. The line that silences the error is: `if ( strlen( @inet_pton( $matches[1] ) ) === 16 ) {`

`$matches[1]` is an IPv4 or IPv6 returned from the server in a unique edge case with dual stacked DNS, when the server has IPv6 enabled but doesn't have IPv6 connectivity. [`inet_ntop`](http://php.net/manual/en/function.inet-pton.php) will return `false` on an invalid IP value but by definition, it also throws an uncatchable PHP warning. If we remove the silencing `@` it will lead to unexpected warnings for sites that have the described server configuration.

cc: @pattonwebz

**Comment by vovafeldman** [comment]
`FILE: /freemius/includes/managers/class-fs-admin-menu-manager.php`:

This file is responsible for the plugin/theme's WP Admin settings menu item(s). The globals override logic is NOT executed for WordPress.org themes. Since we manage only one SDK, the logic is there. To avoid this Theme Check false-positives, I've added a simple alias variables.

Commit ref: 110cf0da0655c2f33fa255cbd0528564375608c3

cc: @pattonwebz

**Comment by vovafeldman** [comment]
`FILE: /freemius/includes/class-freemius.php`:

The last silencing error (line `8188`) is related to `$decoded = @json_decode( $response['body'] );`. When the server is running PHP 5.3, when executing `json_decode()` on an invalid JSON format, the error will be logged silently and can be pulled via [`json_last_error()`](http://php.net/manual/en/function.json-last-error.php). Unfortunately, with PHP 5.2 a warning will be thrown to the screen and can cause unexpected messages and functionality.

cc: @pattonwebz

**Comment by vovafeldman** [comment]
`FILE: /freemius/includes/class-freemius.php`:

Fixed the sliencing in lines `2681`, `2681`.

Commit ref: 1cacb00f2a8dd64cc2f36cd794733aa2ade6ca01

cc: @pattonwebz

**Comment by vovafeldman** [comment]
`FILE: /freemius/includes/l10n.php`

Freemius is loading its own translations and textdomain ('freemius'). To avoid these false-positive textdomain errors from theme check, I've added method aliases as a workaround.

Commit ref: 0a37a2bd52d29d1e072ab1125eae40740cfef89d

cc: @pattonwebz

**Comment by Mirucon** [comment]
Hi!

You can just ignore the issues caused by the PHP version. You can select the PHP version you're going to test with from the drop-down box before you start the test. 

I am glad you are able to fix the issues. It might be a great for theme authors and the WP community.

Thanks
