### ISSUE TITLE
Set notifications on plugin de-activation to idle for 24hrs

### ISSUE THREAD

**Issue by itibook** [Freemius/wordpress-sdk#18]
When de-activating a plugin the notifcation can become annoying especially in a develolpment/maintenance environment (e.g. I am debugging a site and need to turn on/off plugins).

This can produce annoying effects especially if an installation has multiple Freemius enabled plugins.
The user should be allowed to idle notifications if they start getting in the way of his debugging.

A simple "don't bother me for the next 24hrs" should appear if several de-activation are detected.

**Comment by vovafeldman** [comment]
Another idea that was suggested by @itibook is to add a "Cooling-off time period" between one deactivation to another. For example, if the 2nd deactivation of the same plugin happens in less than 10 min after the 1st deactivation - don't show the feedback form.

**Comment by jhabdas** [comment]
I like the cooling off idea. Devs can hack it. Users first.

**Comment by vovafeldman** [comment]
A snoozing option is coming with the next release https://github.com/Freemius/wordpress-sdk/pull/488

![wordpress-sdk-feedback-form-snoozing (1)](https://user-images.githubusercontent.com/6830121/145203999-e44a66c7-d1fc-49dd-a689-202c12e4a39f.gif)
