### ISSUE TITLE
Accept cryptocurrency payments

### ISSUE THREAD

**Issue by jhabdas** [Freemius/wordpress-sdk#184]
**Actual Behavior**:
 -  `What is the issue? (*)` Doesn't offer payment in cryptocurrency
 -  `What is the expected behavior?` Allow payment in Bitcoin or Monero

**Versions**: (*)
 -  `Freemius SDK Version:` n/a
 -  `WordPress Version:` n/a
 -  `PHP Version:` n/a

**Plugin / Theme**: (*)
 -  `Name:` Hyperdrive
 -  `Slug:` hyperdrive
 -  `Freemius ID:` 1109

**Additional Information**:
 -  `Browser Type: (*)` all
 -  `Browser Version: (*)` all
 -  `OS: (*)` all
 -  `Stack Traces:` na/

----

Hey just curious if Freemius is planning to support payments in the form of Bitcoin or a contract-based cryptocurrency such as Ethereum or one of its children altcoins. Thanks!

**Comment by vovafeldman** [comment]
Hey @jhabdas, we are big fans of BitCoin and strongly believe in the blockchain technology. We've been considering to add BitCoin support since Stripe already supports it, though, at the moment, it doesn't support subscriptions, so we decided to wait.
