### ISSUE TITLE
If the API is down during a background sync (once in 24 hours) and there are N freemius powered plugins, it will invoke N failed requests.

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#19]
It also shows N error messages instead of only one message:

![image](https://cloud.githubusercontent.com/assets/6830121/12494949/f14ffcd8-c05a-11e5-9bc2-985f084c9547.png)

Reference: http://community.rtcamp.com/t/freemius-crashing-entire-website/

*The API connection is going crazy. Look at those curl timeouts, 60 seconds per license? 31 rtcamp plugins, 31 * 60 seconds = HOLY SHIT. Site's completely unresponsive since Freemius API server is down or unresponsive. I'm going through and removing all the license checks from the PHP right now.*

**Solution:**
- If the API is down there should only be one error message shown for all Freemius powered plugins.
- The connectivity test should be cached to prevent from the server just waiting for timeouts.

**Comment by nextsteptours** [comment]
Looks like I'm coming in at the right time here.

Before I start, I want to apologize for my extreme lack of knowledge, I am new to this and learning slowly (but at least learning!)

I am coming up with one error and have no idea how to go about fixing it. Any step-by-step help to fix this?

![screen shot 2016-01-21 at 1 59 22 pm](https://cloud.githubusercontent.com/assets/16826461/12495991/c4541132-c047-11e5-9122-712d9ba6f88e.png)

**Comment by vovafeldman** [comment]
@nextsteptours try to close the notice (there's an [X] icon on the top right), then refresh the page and see if it reloads. If not, you are already ok. LMK

**Comment by nextsteptours** [comment]
Ah, amazing. It worked. Easy. Thank you so much! @vovafeldman

**Comment by vovafeldman** [comment]
@nextsteptours the "stickiness" of the message will be fixed for next release so once the API connectivity is back, it will disappear.
