### ISSUE TITLE
Error When using Your Example Plugin

### ISSUE THREAD

**Issue by technofreaky** [Freemius/wordpress-sdk#2]
Hi,

I have used this plugin in my local server https://github.com/Freemius/hello-dolly/tree/master/freemium%20v.1/hello-dolly and i got the below error
![error](https://cloud.githubusercontent.com/assets/1884287/11386876/a646792e-934b-11e5-891f-e8e4af7c6e48.png)

**Comment by fs-contributor** [comment]
The demo plugin was created in a local environment, therefore the plugin don't exist on Freemius production database. What you would need to do is follow the [Hello Dolly screencast](https://www.youtube.com/watch?v=gj6aoYG4fUI) to create a plugin in **your** dashboard, and then replace the SDK init code with the one in the example.
