### ISSUE TITLE
Empty "Payments" section of Account page

### ISSUE THREAD

**Issue by cliffordp** [Freemius/wordpress-sdk#204]
**Actual Behavior**:
 -  `What is the issue? (*)` I generated a new license for an existing user (myself) via Dashboard. I entered the license and it worked and redirected me to the Account page. It had a lot of empty Payments.
 -  `What is the expected behavior?` There shouldn't be any Payments if I haven't made any.

![image](https://user-images.githubusercontent.com/1812179/33097138-d03dc82a-cece-11e7-94dd-d4682acfb4d3.png)

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.2.9
 -  `WordPress Version:` 4.9
 -  `PHP Version:` 7.1

**Plugin / Theme**: (*)
 -  `Name:` TK Event Weather for The Events Calendar
 -  `Slug:` tk-event-weather-the-events-calendar
 -  `Freemius ID:` 241

**Comment by vovafeldman** [comment]
Thanks @cliffordp - we already fixed it in the `develop` branch (related to caching), will be released in the next version.
