### ISSUE TITLE
Symlinks dont work if destination not the plugin name

### ISSUE THREAD

**Issue by alanef** [Freemius/wordpress-sdk#205]
**Actual Behavior**:
 -  `What is the issue? (*)`
ln -s /path_to/plugin-name-project/src   plugin-name
returns empty $sdk_symlink on line 423 of start.php so no symlink path set and SDK fails to load 

ln -s /path_to/plugin-name-project/plugin-name   plugin-name
works as expected

 -  `What is the expected behavior?`
SDK path to be resolved

**Versions**: (*)
 -  `Freemius SDK Version:`
1.2.2.9
 -  `WordPress Version:`
4.9.1
 -  `PHP Version:`
7.0.1

**Plugin / Theme**: (*)
 -  `Name:`
Any
 -  `Slug:`
Any
 -  `Freemius ID:`
Any

**Additional Information**:
 -  `Browser Type: (*)`
Any
 -  `Browser Version: (*)`
Any
 -  `OS: (*)`
Linux
 -  `Stack Traces:`
NA

Not critical - as a development nice to have ( e.g. standard src / dist folders withing project folder ) work around is simply to rename the src folder  to the plugin-name. However issues are not obvious if you have other test plugin that have successfully loaded they SDK due to the avoidance of multi loading by the SDK

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vovafeldman** [comment]
@alanef can you please try testing it with the latest `develop` branch? We made a lot of symlink related changes that we are about to release soon, I just want to avoid wasting time on something that we've already resolved.

**Comment by alanef** [comment]
Sure will do

**Comment by alanef** [comment]
Look fixed in 1.2.2.10

Any idea on release date, just for information.
