### ISSUE TITLE
Warning: fopen - Wrong plugin main path

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#212]
**Actual Behavior**:
 -  `What is the issue?` If the plugin's directory changed for any reason from a previous activated state, there will be a `Warning: fopen` error. We have encountered a number of customers having this issue.
 -  `What is the expected behavior?` No error

Steps to reproduce:
1. Install & activate a plugin with Freemius
2. Change the plugin's folder name
3. Refresh the plugin list admin page (the plugin will deactivate)
4. Activate the plugin again, the error will appear.

I think a previously saved path name is producing the error. Workaround is to go to `/wp-admin/admin.php?page=freemius` and delete the accounts - which is not a good fix.

**Plugin / Theme**: (*)
 -  `Name:` Page Builder Sandwich
 -  `Slug:` page-builder-sandwich
 -  `Freemius ID:` 203

**Additional Information**:
 -  `Stack Traces:`
![image](https://user-images.githubusercontent.com/1033611/35078949-cb437bf0-fc3f-11e7-9fd9-d8edffab4d3a.png)

Traced back to this code:

	$plugin_data = get_plugin_data(
		$this->_plugin_main_file_path,
		false,
		false
	);

`$this->_plugin_main_file_path` holds the wrong path name.

**Comment by vovafeldman** [comment]
Are you using the latest SDK release?

**Comment by bfintal** [comment]
I think it's fixed!
