### ISSUE TITLE
Missing premium plugin logo thumbnail in the updates page

### ISSUE THREAD

**Issue by ruiguerreiro79** [Freemius/wordpress-sdk#214]
**Actual Behavior**:
 -  The logo thumbnail of the Premium Plugin version doesn't show up, showing a generic plugin icon.
 -  It should show the Plugin Logo?

**Versions**: (*)
 -  Freemius SDK Version: Latest
 -  WordPress Version: Latest 
 -  PHP Version: Latest

Screenshot of the issue:

![image](https://user-images.githubusercontent.com/29898220/35516123-d75eaede-0502-11e8-8a11-3fd6bacc2f7b.png)

**Comment by ruiguerreiro79** [comment]
Adding the extra lines in the class-fs-plugin-updater.php sorts it, we just need to replace the $plugin_icon_url value with the specific logo url.

Check here my modification
[https://gist.github.com/ruiguerreiro79/58741cc45241af904b4e6792c58586f2]

**Comment by ruiguerreiro79** [comment]
Also realized that is missing the value for the latest compatibility version.

![image](https://user-images.githubusercontent.com/29898220/35520256-7236c54e-050e-11e8-9338-9d4aa38a3cb5.png)

These 2 lines in red seem to sort it.

![image](https://user-images.githubusercontent.com/29898220/35520335-a4b67668-050e-11e8-87d3-4501acfef398.png)

**Comment by vovafeldman** [comment]
Resolved here https://github.com/Freemius/wordpress-sdk/commit/e6b0f8fd472cd2d255e9f9d59b7e028fe68ca7d1

Will be released in the next version.
