### ISSUE TITLE
Network Activation Issue

### ISSUE THREAD

**Issue by asharirfan** [Freemius/wordpress-sdk#216]
**Actual Behavior**:
 -  `Issue:` I just integrated the code on the `feature/multi-site` branch with our plugin WP Security Audit Log. When I try to `Network Activate` the plugin, I am getting – "Sorry, you're not allowed to access this page." – error. 

## Screencast:
![alt text](https://cl.ly/pLWW/💯 "Screencast")

When I come back to my network dashboard, the plugin is already active. If I try to click on the **Opt-in** link of Freemius in the notice, then I get the same – not allowed error – page again.

Any idea why is this happening?

**Versions**: (*)
 -  `Freemius SDK Version:` 2.0.0
 -  `WordPress Version:` 4.9.4
 -  `PHP Version:` 7.1.7

**Plugin / Theme**: (*)
 -  `Name:` WP Security Audit Log
 -  `Slug:` wp-security-audit-log
 -  `Freemius ID:` 94

**Additional Information**:
 -  `Browser Type: (*)` Google Chrome
 -  `Browser Version: (*)` 64.0.3282.140
 -  `OS: (*)` macOS Sierra v10.12.6

**Comment by vovafeldman** [comment]
@closed due to wrong integration params.
