### ISSUE TITLE
lack of 'Expect' header parameter causes failure of GET request

### ISSUE THREAD

**Issue by vb87** [Freemius/wordpress-sdk#218]
**Actual Behavior**:
 -  `What is the issue? (*)`
Freemius does not connect to the api server (freemius debug shows API status as "BLOCKED")
the issue only seems to bother activation of a new plugin

 -  `What is the expected behavior?`
Should be able to connect to api.freemius.com

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.4 (latest master branch)
 -  `WordPress Version:` 4.9.4
 -  `PHP Version:` 5.4.12

**Plugin / Theme**: (*)
 -  `Name:` not applicable
 -  `Slug:` not applicable
 -  `Freemius ID:` not applicable

**Additional Information**:
 -  `Browser Type: (*)` Chromium
 -  `Browser Version: (*)` 64.0.3282.140 (Official Build) (64-bit)
 -  `OS: (*)` Windows 10
 -  `Stack Traces:`

----

The issue is caused by lack of parameter for the "Expect" HTTP header of the api request.
File: \freemius\includes\sdk\FreemiusWordPress.php
Line: 395
`$pWPRemoteArgs['headers']['Expect'] = '';`
changing to
`$pWPRemoteArgs['headers']['Expect'] = '100-continue';`
fixes the issue

you can test here:
https://www.hurl.it/
requesting https://api.freemius.com/ with added header "Expect", but empty parameter will cause:
 417 EXPECTATION_FAILED 
could be a recent web server update

**Comment by vovafeldman** [comment]
@vb87 this is very strange for a few reasons:
1. We didn't receive any complaints about that and I just tested a plugin that uses Freemius, no issues.
2. When I use hurl.it as you suggested, I indeed see the issue.
3. We haven't made server changes recently.

So I'm not quite sure what's going on. Can you try to reproduce the issue again from your product?

**Comment by vb87** [comment]
this line of code which sets the 'Expect' header value to a zero length string appears to be used only in few specific scenarios, you can easily test it - just put a php 'die' statement after that line, like this:
```
			$pWPRemoteArgs['headers']['Expect'] = '';
			die('!!!');
```

it won't even be called when installing plugin, it appears to be called when deactivating, the other scenario seems like could be either:

1. when plugin is installed for first time on server

**Comment by vovafeldman** [comment]
@vb87 almost every API request uses is. We'll try to reproduce it on our end, thanks.

**Comment by vb87** [comment]
cURL was installed, but not enabled, so version I believe would be irrelevant
