### ISSUE TITLE
Rename "Downgrade" button in "Cancel Subsription"

### ISSUE THREAD

**Issue by Dudo1985** [Freemius/wordpress-sdk#224]
**Actual Behavior**:
 -  `What is the issue? (*)`
I've addon that has only premium plan, so the "Dowgrade" button is just wrong

 -  `What is the expected behavior?`
Use a button with "Cancel Subscription" (or similar)

**Versions**: (*)
 -  `Freemius SDK Version:` Any
 -  `WordPress Version:` Any
 -  `PHP Version:` Any

**Plugin / Theme**: (*)
 -  `Name:` Any
 -  `Slug:` Any
 -  `Freemius ID:`

**Additional Information**:
 -  `Browser Type: (*)` --
 -  `Browser Version: (*)` --
 -  `OS: (*)` --
 -  `Stack Traces:`

![schermata del 2018-03-14 15-23-11](https://user-images.githubusercontent.com/5710734/37408604-ba4470d8-279c-11e8-9334-4db263d65bc8.png)

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vovafeldman** [comment]
Fixed in the `develop` branch: 7d532a9896f6093e801712d29a2e75ec9a1f35e6

Will be officially released soon.
