### ISSUE TITLE
Need a method to opt out once opted in.

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#23]

**Comment by vovafeldman** [comment]
The user can opt-out by clicking the **Delete** link on the **Account** section. Or do you mean something else?

**Comment by danieliser** [comment]
Hmm, must have missed that. Can it also be done programmatic-ally if the account tab is hidden?

**Comment by vovafeldman** [comment]
Yes, you can execute: `freemius()->delete_account_event();`

**Comment by danieliser** [comment]
Looks like this finally got added in the way I envisioned ;)
