### ISSUE TITLE
Version 1.10 showing as 1.1 in dashboard

### ISSUE THREAD

**Issue by alanef** [Freemius/wordpress-sdk#244]
**Actual Behavior**:
 -  `What is the issue? (*)`  When loading up a version 1.10   the dashboard showed 1.1
 -  `What is the expected behavior?` show 1.1

**Versions**: (*)
 -  `Freemius SDK Version:` 2.2.1
 -  `WordPress Version:` 4.9.6
 -  `PHP Version:` 7.0

**Plugin / Theme**: (*)
 -  `Name:` Widget for Event Brite API
 -  `Slug:` widget-for-eventbrite-api
 -  `Freemius ID:` 1330

**Additional Information**:
 -  `Browser Type: (*)`  Chrome
 -  `Browser Version: (*)` 67
 -  `OS: (*)`  Debian
 -  `Stack Traces:`

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

Didn't risk releasing, just skipped 1.10 to 1.11

**Comment by vovafeldman** [comment]
@alanef do you mean that after deploying a plugin versioned as 1.10 to the dashboard it shows as 1.1?

**Comment by alanef** [comment]
Yes, my typo  1.10 shows as 1.1

**Comment by vovafeldman** [comment]
@alanef this can happen when initializing the SDK too late. The SDK snippet needs to be executed right when the plugin/theme's code is executed.
