### ISSUE TITLE
Clone Error on PHP 7.1

### ISSUE THREAD

**Issue by zourbuth** [Freemius/wordpress-sdk#246]
**Actual Behavior**:
 -  `‘clone’ is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)`
 -  https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L15572

**Versions**: (*)
 -  `Freemius SDK Version: 2.0.1`
 -  `WordPress Version: 4.9.6`
 -  `PHP Version: 7.1`

**Comment by bradvin** [comment]
have you tried updating to SDK v2.1.1? A customer of mine has reported this error and wondering if the latest SDK will resolve this issue. @vovafeldman any ideas?

**Comment by vovafeldman** [comment]
@zourbuth this is the line that I see in 2.0.1:
https://github.com/Freemius/wordpress-sdk/blob/2.0.1/includes/class-freemius.php#L15572

![image](https://user-images.githubusercontent.com/6830121/43412982-6a2d81e0-9437-11e8-87aa-7901fe8fbe91.png)

Are you sure it's the right line?

**Comment by vovafeldman** [comment]
@zourbuth @bradvin can you please try to open `class-freemius.php`, and replace:
```
$encrypted_site = clone ( is_object( $site ) ? $site : $this->_site );
```

with:
```
$site_clone = is_object( $site ) ? $site : $this->_site;
$encrypted_site = clone $site_clone;
```

and let me know if that resolved the error?

**Comment by bradvin** [comment]
@vovafeldman I can confirm that making your suggested change resolved the error

**Comment by vovafeldman** [comment]
Changed committed https://github.com/Freemius/wordpress-sdk/commit/82cdedd4853778298e821b9b3c0e1d46a758f073

Will be merged to the next release.
