### ISSUE TITLE
Updating Options on each page load ( ~150ms load )

### ISSUE THREAD

**Issue by igorbenic** [Freemius/wordpress-sdk#260]
**Actual Behavior**:
 -  On each page load the <code>FS_Option_Manager</code> updates the <code>fs_accounts </code> option resulting in double queries and also adding around 120-150ms to the load time

**Versions**: (*)
 -  Freemius SDK Version: 2.1.1
 -  WordPress Version: 4.9.8
 -  PHP Version: 7.1.1

**Plugin / Theme**: (*)
 -  Name: Simple Giveaways
 -  Slug: giveasap
 -  Freemius ID: 396

<img width="1430" alt="screen shot 2018-09-25 at 11 26 16" src="https://user-images.githubusercontent.com/1537130/46005950-b058f180-c0b6-11e8-842c-f926b1780938.png">

Is this done only for the logged-in user?

I got a customer reporting this and he is concerned about the performance of his site since he says that only this plugin is creating a performance hit. I've gone through the whole plugin and it seems that this part triggers on every page load.

**Comment by vovafeldman** [comment]
@igorbenic this should not happen. If you can contact our support [support AT freemius DOT com] with FTP + WP Admin access, we can investigate to understand why an update is triggered upon every request.

**Comment by vovafeldman** [comment]
Closing due to lack of response.
