### ISSUE TITLE
Freemius optin interrupts Gutenberg layout

### ISSUE THREAD

**Issue by Shelob9** [Freemius/wordpress-sdk#265]
**Actual Behavior**:
 -  The Freemius optin gets in the way of post editor.

**Versions**: (*)
 -  `Freemius SDK Version:`
WordPress Version: 4.9.8
PHP Version: 7.0.32-0ubuntu0.16.04.1

Caldera Forms Version: 1.7.2
Gutenberg 3.9

----
Please see: https://github.com/CalderaWP/Caldera-Forms/issues/2740 Includes screenshots

**Comment by alanef** [comment]
@vova 5.0 is live and the notice makes it look buggy https://drive.google.com/file/d/1RofgMO-wJr1vLxgw-F788VE1oVeGaeTQ/view

WordPress guideline suggest only displaying on dashboard, plugins, tools. settings and the settings page, so for my admin notices I do

`
$page             = get_current_screen()->base;
$display_on_pages = array(
			'dashboard',
			'plugins',
			'tools',
			'options-general',
			'settings_page_whatever',
		);
		if ( ! in_array( $page, $display_on_pages ) ) {
			return;
		}`

But you could do something like make a filterable exclusion list - I think the editor appears on post
`$page             = get_current_screen()->base;
$display_not_on = array(
			'post'
		);
		if ( ! in_array( $page, apply_filters('hide_fs_notices',$display_not_on )) ) {
			return;
		}`

**Comment by alanef** [comment]
p.s.  I put a pull request in develop to fix this  see https://github.com/Freemius/wordpress-sdk/pull/290
