### ISSUE TITLE
Dashboard: Billing Info Auto Save Delay

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#29]
The auto save is great but it fires for every field with no delay. Even when I fill in fields very quickly it ques up each fields save in succession.

Propose setting a delay timeout that can be cleared on focus out. Then when multiple fields are filled you only send one request.

Will also make using tools like google chrome form filler more efficient.

**Comment by vovafeldman** [comment]
I'm not aware of any auto-save. Maybe you can describe the experience you are having and explain why should it change?

**Comment by danieliser** [comment]
dashboard.freemius.com then go to where you update billing info.

Should have specified your dash not plugin dash.

**Comment by vovafeldman** [comment]
The auto-save only fires on blur. But yes, it happens on every field.

In any case, I'm closing this ticket since this project is about the WordPress SDK. Next time please email support@freemius.com regarding dashboard related issues/suggestions/feedback.
