### ISSUE TITLE
Freemius admin notices get hidden behind the Block Editor

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#292]
**Actual Behavior**:
 -  `What is the issue? (*)` 
If there's a Freemius admin notice present, they get hidden behind the block editor and cannot be dismissed. For example (the opacity of the bar was added to show what's behind it):

![screen shot 2018-12-12 at 5 45 32 pm](https://user-images.githubusercontent.com/1033611/49860972-ce243000-fe35-11e8-89c8-d83660600bf6.jpg)

 -  `What is the expected behavior?`
The notice should be below the bar similar to how normal admin notices would be placed.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.2.2
 -  `WordPress Version:` 5.0
 -  `PHP Version:` 7.2

**Comment by vovafeldman** [comment]
Duplicate #265
