### ISSUE TITLE
Calling images remotely is not allowed!

### ISSUE THREAD

**Issue by ahmadawais** [Freemius/wordpress-sdk#3]
My plugin got disabled due to the fact that Freemius was calling images from SVN which is not allowed as per the [guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/).

I found these links (which I already had in commented form) in the following two files.

- https://github.com/Freemius/wordpress-sdk/blob/master/freemius/templates/pending-activation.php#L37-L44
- https://github.com/Freemius/wordpress-sdk/blob/master/freemius/templates/connect.php#L39-L45

**Comment by irkanu** [comment]
@ahmadawais That sucks. :( I'm currently trying to integrate my free plugin with Freemius to gain some useful insight into my users. May I ask which plugin you've integrated, so I may learn from it?

Is this the infringing piece of the guidelines?

> All images and scripts shown should be part of the plugin. These should be loaded locally. If the plugin does require that data is loaded from an external site (such as blocklists) this should be made clear in the plugin’s admin screens or description. The point is that the user must be informed of what information is being sent where.

**Comment by vovafeldman** [comment]
We are on it! Apologies for the inconvenience.

**Comment by ahmadawais** [comment]
@irkanu Yeah it does. I am sure @vovafeldman  would get things straightened out as soon as possible. You are right, there were calls to svn and 3rd party urls for images. 

>### System Abuse
Your plugin is calling images from WordPress.org:
`//plugins.svn.wordpress.org/<?php echo $slug ?>/assets/icon-256x256.jpg`
We don't permit this as it causes undue load on our system.

>### Calling images remotely
Offloading images to your own server is disallowed.
Please include all images needed for your plugin locally.
`//wimg.freemius.com/plugin-icon.png` for example MUST be inside your plugin

There you go.

**Comment by vovafeldman** [comment]
Fixed! The plugin's featured icon would be now automatically fetched from the repo ONCE, and only during the developer's local testing. The icon would be fetched to /freemius/assets/img/icon.{extension). So after deploying, the icon would be included in the assets and loaded from the local WP install.

Please update to the new master.
