### ISSUE TITLE
Change the name of the menu page

### ISSUE THREAD

**Issue by Mte90** [Freemius/wordpress-sdk#30]
Case example:
I create a page with `add_menu_page` and set as name the Plugin name.
Freemius transform that menu page in a parent menu page, so in the sidebar we have the plugin name and in that a sub menu with a page with the name of the plugin name.
In my case I want that page have a different name like settings.

Actual situation:
![screenshot6](https://cloud.githubusercontent.com/assets/403283/13081868/b460cf7c-d4ce-11e5-8e84-097afc0515f4.png)

What I want:
![screenshot7](https://cloud.githubusercontent.com/assets/403283/13081869/b5fc915e-d4ce-11e5-840a-ae7a5a37aa17.png)

**Comment by vovafeldman** [comment]
I'm not sure I understand, do you say that Freemius rename the first submenu item to the top level menu title?

Here's a plugin that uses Freemius and has the same situation, the menu item's title is **RatingWidget** while the first submenu item is **Settings**:
![image](https://cloud.githubusercontent.com/assets/6830121/13087572/9b2895ac-d4b6-11e5-85ff-89fb74d09d43.png)

**Comment by Mte90** [comment]
Uhm because that plugin have sub menu page but my plugin have only add_menu_page like the screenshot.

**Comment by vovafeldman** [comment]
I see. How about adding a submenu page, in addition to the page, and naming it 'Settings'. I know it doesn't make sense if not using Freemius, but in the current case, it should do the job. What do you think?

**Comment by Mte90** [comment]
Well for me is more simple do like the screenshot, rename the page on the fly with the plugin name in settings (get that value from `fs_dynamic_init`)
