### ISSUE TITLE
Suggest  an improvement to handling activation of free when premium is already active

### ISSUE THREAD

**Issue by alanef** [Freemius/wordpress-sdk#302]
**Actual Behavior**:
 -  `What is the issue? (*)`

     snippet to de-activate free works
        if ( function_exists( 'xxxxxxx_fs' ) ) {
              xxxxxxx_fs()->set_basename( true, __FILE__ );
        return;
            }

     However,  once the premium is active, you can activate the free version - with some rather strange results 

 -  `What is the expected behaviour?`

    A suggested improvement would be to detect that the premium is active when  the free is being reactivated  and die with a message - cant activate free while premium active ......

    I have tried a few attempts at coding this but didn't get a way that appeared to work.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.2.3
 -  `WordPress Version:` 5.0.3
 -  `PHP Version:`  7.2

**Plugin / Theme**: (*)
 -  `Name:`   Any
 -  `Slug:` Any
 -  `Freemius ID:` Any

**Additional Information**:
 -  `Browser Type: (*)` Any
 -  `Browser Version: (*)` Any
 -  `OS: (*)` Any
 -  `Stack Traces:`  NA

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vovafeldman** [comment]
@alanef activation of the free version when the premium is activated supposed to auto-deactivate the premium version. Is it reproducible?

**Comment by alanef** [comment]
Yes it was reproducible - I created minimal plugins to check.   I'll see if I still have them.

**Comment by alanef** [comment]
OK I have rebuilt the simplest test on 5.1  and SDK 2.2.4  and indeed the activate / deactivate does work both ways.   Probably something wrong with my end when I noticed it first.  Closing.
