### ISSUE TITLE
Warning: sprintf(): Too few arguments

### ISSUE THREAD

**Issue by bfintal** [Freemius/wordpress-sdk#304]
**Actual Behavior**:
I saw this today in my plugins page:

> Warning: sprintf(): Too few arguments in /home/.../freemius/includes/class-fs-plugin-updater.php on line 306

**Versions**: (*)
 -  `Freemius SDK Version:` 2.2.3
 -  `WordPress Version:` 5.1
 -  `PHP Version:` 7.2

**Plugin / Theme**: (*)
 -  `Name:` Stackable
 -  `Slug:` stackable-ultimate-gutenberg-blocks
 -  `Freemius ID:` 1748

**Comment by vovafeldman** [comment]
@bfintal this one is already fixed in the develop branch and will be merged into the next release. Thanks!

**Comment by vovafeldman** [comment]
@bfintal the fix was deployed with the last release.
