### ISSUE TITLE
Notice: Trying to get property 'premium_slug' of non-object in includes/class-freemius.php

### ISSUE THREAD

**Issue by bologer** [Freemius/wordpress-sdk#309]
**Actual Behavior**:
 -  `What is the issue? (*)`

```
Notice: Trying to get property 'premium_slug' of non-object in includes/class-freemius.php on line 5324
```
 -  `What is the expected behavior?`
Not to have notice.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.2.4
 -  `WordPress Version:` 5.1
 -  `PHP Version:` 7.2

**Plugin / Theme**: (*)
 -  `Name:` AnyComment
 -  `Slug:` anycomment
 -  `Freemius ID:` 2926

**Additional Information**:
 -  `Browser Type: (*)` Firefox for Linux
 -  `Browser Version: (*)` 65.0.1 (64-bit)
 -  `OS: (*)` Linux Mint
 -  `Stack Traces:` 
```
Notice: Trying to get property 'premium_slug' of non-object in includes/class-freemius.php on line 5324
```

**Comment by bologer** [comment]
Seems to be related to #291, but a bit different cause

**Comment by vovafeldman** [comment]
@bologer can you please share your integration snippet code? (don't forget to remove the secret key if it's visible)

**Comment by vovafeldman** [comment]
@bologer I'm closing this one due to lack of activity. If that is still happening, please re-open and include the integration snippet as mentioned at [this comment](https://github.com/Freemius/wordpress-sdk/issues/309#issuecomment-469319475).
