### ISSUE TITLE
Custom CSS for inside of iFrames

### ISSUE THREAD

**Issue by Shelob9** [Freemius/wordpress-sdk#32]
I really need a way to add a custom CSS to the pricing sign up and contact iFrames that are being served from your site. Even if I just pass a file path in the settings.

**Comment by bfintal** [comment]
+1

Or a field for adding CSS in the Settings section in the Dashboard.

**Comment by iconicwp** [comment]
+1 Encouragement!

**Comment by vovafeldman** [comment]
Will be deployed in the upcoming release.

**Comment by vovafeldman** [comment]
We've deployed the support for custom CSS in the in-dashboard pricing and checkout pages:
![image](https://cloud.githubusercontent.com/assets/6830121/19412143/338f135e-92dd-11e6-869b-71c1f9afa741.png)

**Disclaimer:** Changes in the iframes' HTML DOM structure can affect your customization. Hence, we do NOT recommend setting custom CSS. So use it at your own risk.
