### ISSUE TITLE
Uncaught Error: Call to undefined function get_blog_list()

### ISSUE THREAD

**Issue by igorbenic** [Freemius/wordpress-sdk#345]
I've just got this email from my site that my premium plugin caused an error. The email was sent from WP 5.2 new error detection system.

Users on WP 5.2 could get such emails and think that my premium plugin is causing the issue.

**Actual Behavior**:
 -  `What is the issue? (*)`
This is what I got in the email:
````
An error of type E_ERROR was caused in line 12628 of the file /.../wp-content/plugins/giveasap-premium/freemius/includes/class-freemius.php. 
Error message: Uncaught Error: Call to undefined function get_blog_list() in /.../wp-content/plugins/giveasap-premium/freemius/includes/class-freemius.php:12628
````

**Versions**: (*)
 -  `Freemius SDK Version:` 2.2.4
 -  `WordPress Version:` 5.2.1
 -  `PHP Version:` 7.2

**Plugin / Theme**: (*)
 -  `Name:` Simple Giveaways
 -  `Slug:` giveasap
 -  `Freemius ID:` 396

**Additional Information**:
 -  `Stack Traces:`

```
Stack trace:
#0 /.../wp-content/plugins/giveasap-premium/freemius/includes/class-freemius.php(12697): Freemius::get_sites()
#1 /.../wp-content/plugins/giveasap-premium/freemius/includes/class-freemius.php(17035): Freemius->get_blog_install_map()
#2 /.../wp-content/plugins/giveasap-premium/freemius/includes/class-fs-plugin-updater.php(122): Freemius->has_any_active_valid_license()
#3 /.../wp-content/plugins/giveasap-premium/freemius/includes/class-fs-plugin-updater.php(72): FS_Plugin_Updater->filters()
#4 /.../wp-content/plugins/giveasap-premium/freemius/includes/class-fs-plugin-updater.php(59): FS_Plugin_Updater->__construct(Object(Freemius))
#5 /s
```

I've found the code that is triggering the error. The issue is that on a single site installation, the multisite functions are not available. So the function get_sites on WP 5.2.1 is not available if the site is not on a multisite.

https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L12620-L12629

**Comment by vovafeldman** [comment]
@igorbenic this one was already fixed in [2.3.0](https://github.com/Freemius/wordpress-sdk/releases/tag/2.3.0)
