### ISSUE TITLE
If plan isn't set a property is attempted to be retrieved from the non-object $_site

### ISSUE THREAD

**Issue by Shelob9** [Freemius/wordpress-sdk#35]
L3902 in Freemius class.

**Comment by vovafeldman** [comment]
Can you reproduce that? There shouldn't be a case when there's no plan set.

**Comment by Shelob9** [comment]
I had a plan set, and then I clicked the reset license button.
It might be an edge case beacuse the plan I had set before no longer exists. Still, `is_object( $this->_site->plan )` is an insufficient check since it's checking `$_plan` which might not be accessible.

**Comment by Shelob9** [comment]
@vovafeldman I'm getting this issue on a fresh install. Same errors.
