### ISSUE TITLE
Beta tries to enqueue a missing css file

### ISSUE THREAD

**Issue by alanef** [Freemius/wordpress-sdk#351]
**Actual Behavior**:
 -  `What is the issue? (*)` WP SDK Tries to en-queue a css file which is is missing creating a  404

line 1742 of /includes/class-freemius.php

```       static function _maybe_add_beta_label_styles() {
            $has_any_beta_version = false;

            foreach ( self::$_instances as $instance ) {
                if ( $instance->is_beta() ) {
                    $has_any_beta_version = true;
                    break;
                }
            }

            if ( $has_any_beta_version ) {
                fs_enqueue_local_style( 'fs_plugins', '/admin/plugins.css' );
            }
        }
```
 -  `What is the expected behavior?` Either the plugins.css file to exist  if needed - of not to enqueue it if not ..

**Versions**: (*)
 -  `Freemius SDK Version:` 2.3.0
 -  `WordPress Version:` 5.2.1
 -  `PHP Version:` All

**Plugin / Theme**: (*)
 -  `Name:` All
 -  `Slug:` All
 -  `Freemius ID:` All

**Additional Information**:
 -  `Browser Type: (*)` Any
 -  `Browser Version: (*)` Any
 -  `OS: (*)` Any
 -  `Stack Traces:` N/A

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vovafeldman** [comment]
This one was fixed back in July https://github.com/Freemius/wordpress-sdk/commit/af61f3075bffe6c2dd3f39e8a57e22af144e6523
