### ISSUE TITLE
Show the license activation link for "serviceware" plugins/themes even in the free code base

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#356]
**Actual Behavior**:
 -  `What is the issue? (*)`
     If a user didn't opt-in to a serviceware product there's no way for them to activate the license before opting in.
 -  `What is the expected behavior?`
     They should have a way to do it.

![image](https://user-images.githubusercontent.com/6830121/60669891-15c4e480-9e78-11e9-8c0c-23aa05e3374b.png)

**Versions**: (*)
 -  `Freemius SDK Version:` 2.3.0

**Comment by vovafeldman** [comment]
Fix https://github.com/Freemius/wordpress-sdk/commit/19e86846db1ae706b26330d2765e92991f1cf44c

**Comment by cyberhobo** [comment]
I have a user who downgraded to a free plan but is now confused by this link, thinking he is required to buy a license again.
