### ISSUE TITLE
i18n: Japanese locale is `ja` not `ja_JP`

### ISSUE THREAD

**Issue by tomonic-x** [Freemius/wordpress-sdk#359]
`languages​/freemius-ja_JP.mo` is not used in the Japanese locale ` ja`.

In WordPress, Japanese locale is `ja` not `ja_JP`.
https://make.wordpress.org/polyglots/teams/

Please rename `languages​/freemius-ja_JP.*` to `languages​/freemius-ja.*`.

**Comment by vovafeldman** [comment]
@tomonic-x thanks, will be fixed in the upcoming SDK release.
