### ISSUE TITLE
Fatale Error on plugin activation

### ISSUE THREAD

**Issue by sebastienserre** [Freemius/wordpress-sdk#371]
# 🐞 bug report

**Behavior**:
When I activate one of my Pugin on a WordPress site, got the error:
```Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/thiverval-grignon/wp-content/plugins/wp-dashboard-premium/freemius/includes/managers/class-fs-key-value-storage.php:154 Stack trace: #0 /var/www/thiverval-grignon/wp-content/plugins/wp-dashboard-premium/freemius/includes/managers/class-fs-key-value-storage.php(129): FS_Key_Value_Storage->load() #1 /var/www/thiverval-grignon/wp-content/plugins/wp-dashboard-premium/freemius/includes/managers/class-fs-key-value-storage.php(107): FS_Key_Value_Storage->__construct('admin_notices', 'global', 0) #2 /var/www/thiverval-grignon/wp-content/plugins/wp-dashboard-premium/freemius/includes/managers/class-fs-admin-notice-manager.php(123): FS_Key_Value_Storage::instance('admin_notices', 'global', 0) #3 /var/www/thiverval-grignon/wp-content/plugins/wp-dashboard-premium/freemius/includes/managers/class-fs-admin-notice-manager.php(93): FS_Admin_Notice_Manager->__construct('global', '', '', false, 0) #4 /var/www/thiverval-grignon/wp-content/plugins/wp-dashboa in /var/www/thiverval-grignon/wp-content/plugins/wp-dashboard-premium/freemius/includes/managers/class-fs-key-value-storage.php on line 154```

**Versions**: (*)
 -  `Freemius SDK Version:`  2.3.1
 -  `WordPress Version:`  5.2.4
 -  `PHP Version:`  7.3.10-1+0~20191008.45+debian9~1.gbp365209

**Plugin / Theme**: (*)
 -  `Name:` Dashboard WP
 -  `Slug:`  wp-dashboard-premium
 -  `Freemius ID:` 4459

**Additional Information**:
 -  `Browser Type: (*)`
 -  `Browser Version: (*)`
 -  `OS: (*)`
 -  `Stack Traces:`

**Comment by sebastienserre** [comment]
I found this...

**Comment by tillkruss** [comment]
Make sure you remove the JSON serializer from you config and then flush the Redis database.

**Comment by sebastienserre** [comment]
Yes I have done this.

**Comment by sebastienserre** [comment]
Thanks to @vovafeldman 
https://github.com/Freemius/freemius-fixer solved this cache problem
