### ISSUE TITLE
Add plugin 'Settings' tab to list of Freemius tabs

### ISSUE THREAD

**Issue by dgwyer** [Freemius/wordpress-sdk#384]
# 🚀 feature request

### Description
When using the new tabs feature via the SDK integration snippet `'navigation' => 'tabs'` I think there should be an extra tab added if the plugin has a settings page. This is the current view.

![current](https://user-images.githubusercontent.com/1482075/71587482-bf2e1f80-2b15-11ea-8ff4-fdece9a1ce20.png)

Also, at the moment there is no way via the tabs to get back to the plugin settings. You're forced to click on the main plugin submenu item under 'Settings'.

![current-subpage](https://user-images.githubusercontent.com/1482075/71587486-c6552d80-2b15-11ea-8d32-085ddd1e6bab.png)

### Describe the solution you'd like
When a plugin has a setting page defined, it would make sense to add a 'Settings' tab that is active by default when the main plugin submenu link is clicked. (The 'Settings' tab label should also be filterable for flexibility.)

![proposed](https://user-images.githubusercontent.com/1482075/71587490-cd7c3b80-2b15-11ea-842e-41820c88e897.png)

Adding this tab would also provide an easy way to navigate back to the main settings page.

![proposed-subpage](https://user-images.githubusercontent.com/1482075/71587534-f4d30880-2b15-11ea-9786-a23034c3953c.png)

I don't think there needs to be a submenu link added for the default 'Settings' tab as this is effectively the homepage for the plugin settings. For other tabs adding an extra submenu link makes sense to indicate which page you're on.

I'm hoping this proposal shouldn't be too difficult to add as most of the work to implement tabs has already been done.

And it also means that developers would have a really nice way to seamlessly integrate their plugin settings with the Freemius pages. As you can see from the proposed mockups it looks great.

**Comment by alanef** [comment]
As the tab navigation works already with existing tab navigation, it is easy for a plugin author to already add a single settings tab. Indeed I do.  ( I'll dig the code out if you like )

So whilst this change in my opinion, is unnecessary, if it does go ahead, it will need to consider plugins that are already tabbed.

![Selection_285](https://user-images.githubusercontent.com/15021240/71642454-4c52af00-2ca3-11ea-8708-e24fae521e52.png)

**Comment by dgwyer** [comment]
Thanks for the feedback Alan. After discussing this with Vova I now understand that you can add your own tabs quite easily and Freemius takes this into account when rendering the Account, Contact us tabs etc.

I'm going to be writing the documentation for the 'navigation' => 'tabs' feature so I'd be interested in your code and how you've implemented it, so please feel free to share.

**Comment by alanef** [comment]
I thinks each implementation of settings page / pages would be different so just looking at my code I don't think it is generic.

I'll include some code snippets anyway to show how I do it in my settings pages - it is designed to work with many individual settings pages, but works perfectly well with just one ....

The principal is each setting page extends a generic admin page class, and each setting page 'registers' a tab.

`Utilities::get_instance()->register_settings_page_tab( __( 'Settings', 'fullworks-anti-spam' ), 'settings', admin_url( 'admin.php?page=fullworks-anti-spam-settings' ), 0 );
`

the admin page class when it sets up the page loops through the tabs

`<div class="wrap fs-page">

                <h2 class="brand"><?php echo $this->settings_title; ?></h2>

				<?php settings_errors(); ?>


                <div class="fs-settings-meta-box-wrap">

                    <form id="fs-smb-form" method="post" action="options.php">

						<?php settings_fields( $this->option_group ); // options group
						?>
						<?php wp_nonce_field( 'closedpostboxes', 'closedpostboxesnonce', false ); ?>
						<?php wp_nonce_field( 'meta-box-order', 'meta-box-order-nonce', false ); ?>

						<?php $this->display_tabs(); ?>

                        <div id="poststuff">

etc etc ...`

`	public function display_tabs() {
		$split     = explode( "-", $_GET['page'] );
		$page_type = $split[ count( $split ) - 1 ];
		$tabs      = Utilities::get_instance()->get_settings_page_tabs( $page_type );
		if ( count( $tabs ) < 1 ) {
			return;
		}
		?>
        <h2 class="nav-tab-wrapper">
			<?php foreach ( $tabs as $key => $tab ) {
				$active = '';
				if ( preg_match( '#' . $_GET['page'] . '$#', $tab['href'] ) ) {
					$active = ' nav-tab-active';
				}
				echo '<a href="' . $tab['href'] . '" class="nav-tab' . $active . '">' . $tab['title'] . '</a>';
				// <a href="#" class="nav-tab nav-tab-active">Social Options</a>
			}
			?>


        </h2>
		<?php
	}
`

The utility functions are simply thus

`	public function register_settings_page_tab( $title, $page, $href, $position ) {
		$this->settings_page_tabs[ $page ][ $position ] = array( 'title' => $title, 'href' => $href );

	}

	public function get_settings_page_tabs( $page ) {
		$tabs = $this->settings_page_tabs[ $page ];
		ksort( $tabs );

		return $tabs;
	}
`

**Comment by dgwyer** [comment]
Thanks for sharing your implementation. You obviously have a custom setup there but I think the underlying principle would be the same for most use cases.

i.e.

* Set `'navigation' => 'tabs'` in SDK config.
* On your plugin settings pageAdd a `<h2 class="nav-tab-wrapper"></h2>` element manually and add one or more tabs as needed.
* Freemius will then detect the existence of the `h2.nav-tab-wrapper` element and add the Freemius specific tabs (Account, Contact Us etc.).

Would you say that this is the simplified version of the method you've implemented?

If so, are you seeing a brief 'flash' where the hard-coded tabs are rendered immediately, before the other Freemius tabs have been added via JS? I had this issue and was going to solve it by hiding the tab header with CSS initially and only displaying it once all tabs have been rendered.

I'm now actually injecting my custom 'Settings' tab with JS which means all tabs are rendered at once and I don't have to hide anything initially with CSS. I'll be showing both methods in the new docs.

**Comment by alanef** [comment]
Yes, that is it.

But I don't get any flash in normal use, it is true that  the freemius tabs are added by JS but I get no flash unless I deliberately disable browser caching, and even then it is minimal

**Comment by dgwyer** [comment]
It is minimal my end too but some people might find it a little annoying so I may include details on hiding the tab header initially.

Also, injecting custom tabs manually via JS opens up the possibility of rearranging the tab order which some users may find useful.

**Comment by alanef** [comment]
Just a random idea -  Freemius could have a 'register tab' function or filter and then it could apply all tabs inc JS.

This would allow your solution to be painless yet still allow non JS solutions to work...

Now I'm off into the Freemius code - who  knows thee may already be a filter?

**Comment by dgwyer** [comment]
I thought about that but I don't think there is any such filter currently? Looks like a possibility could be if a filter was added to `/freemius/templates/tabs.php` at [line 25](https://github.com/Freemius/wordpress-sdk/blob/master/templates/tabs.php#L25)?

This would then mean that you wouldn't have to manually inject custom tabs, and just add them via this filter instead.

Of course, if you wanted a custom tab order then you'd have to have a filter that executed after the Freemius tabs had been added too.

**Comment by alanef** [comment]
Adding 

      $tabs = apply_filters('freemius_tabs',$tabs);

after line 57 of tabs nearly works perfectly - except detection on active tab ...

     add_filter( 'freemius_tabs', function ( $tabs ) {
			array_unshift( $tabs, [
					'label' => __( 'Settings 2', 'my-plugin' ),
					'href'  => admin_url( 'options-general.php?page=my-settings' ),
					'slug'  => 'settings',
				]
			);
			return $tabs;
		}, 10, 1 );

**Comment by dgwyer** [comment]
Yes, it seems relatively straight forward to add support for custom tabs via a filter except for the active tab. It adds the active tab class via the JS code after line 58 depending on the current Freemius admin page:

    if ($fs->is_admin_page( $tab['slug'] )) {
      ...
      $tabClone.addClass('nav-tab-active');
    }

I think this could be tricky to get to work without some input from Freemius devs who know the system inside out.

**Comment by dgwyer** [comment]
Perhaps if you could set another field via the `'freemius_tabs'` filter that defines what admin page this tab should be active for.

Then, the JS code could first test for Freemius admin pages and then if no matches are found it looks at the extra defined field for the custom tab, and if that matches the current admin page then set the custom tab to active.

**Comment by dgwyer** [comment]
@alanef Out of curiosity when you click on either the Account or Contact Us tabs what classes are present in the `div.wrap` element?

In your custom tab(s) you're manually adding the `fs-page` class. Is this also present when Freemius pages are displayed?

**Comment by dgwyer** [comment]
This is easily do-able now and has been fully documented here: https://freemius.com/help/documentation/wordpress-sdk/tabs-navigation/
