### ISSUE TITLE
Upgrade menu added without paid plans

### ISSUE THREAD

**Issue by irkanu** [Freemius/wordpress-sdk#4]
Summary:
If I don't have paid plans for my plugin, then I shouldn't see the Upgrade menu added.

You can see I've set "has_paid_plans" to false; however, it still adds the submenu.

![code](https://cloud.githubusercontent.com/assets/6570433/11583963/844c1ade-9a2d-11e5-9650-8be675721645.png)

![upgrade_submenu](https://cloud.githubusercontent.com/assets/6570433/11583998/ddf6e6b8-9a2d-11e5-82f2-d18f52503e01.png)

I'll be submitting a commit for this issue soon. Please confirm that this is a bug and I'm not crazy. :)

**Comment by fs-contributor** [comment]
You are not crazy @irkanu :) I presume that the reason it is happening is because you did configure paid plans before, and they were fetched by the API and stored locally. I will help you to clear that cache - can you please share your `fs_dynamic_init()` call? (without the `secret_key`)

**Comment by irkanu** [comment]
@fs-contributor Ahhh. That makes sense. This may close out my pull request if that's the case. :)
```
// Create a helper function for easy SDK access.
function em_fs() {
    global $em_fs;

    if ( ! isset( $em_fs ) ) {
        // Include Freemius SDK.
        require_once dirname(__FILE__) . '/freemius/start.php';

        $em_fs = fs_dynamic_init( array(
            'id'                => '50',
            'slug'              => 'edd-mixpanel',
            'public_key'        => 'pk_11d217df2392ee2d46849790edd82',
            'is_live'           => false,
            'is_premium'        => false,
            'has_addons'        => false,
            'has_paid_plans'    => false,
            'menu'              => array(
                'slug'       => 'edd-mixpanel',
            ),
        ) );
    }

    return $em_fs;
}

// Init Freemius.
em_fs();
```

**Comment by fs-contributor** [comment]
1. Set up the SDK into development mode by modifying `WP_FS__DEV_MODE` to `true` in `config.php` 
2. Load the following page: www.path.to/wp-admin/admin.php?page=edd-mixpanel-account&background_sync=true
3. I added a free level plan for your plugin in the Freemius dashboard, currently the SDK is not "playing" well without any plans.

Please let me know if that cleared the cache.

Also, based on your init function and the screenshots, I suggest setting up a quick skype to understand what are you trying to do. Your current config will NOT override any of the top/sub-menu items with the opt-in screen.

**Comment by irkanu** [comment]
Perfect!

So, from what I understand, this bug was created because I previously had "Paid Plans" from the Freemius Dashboard, but deleted them. It seems after you've added the Free plan it has been resolved :)

Would you like me to test it without the Free plan and clearing the cache? If not, everything is working properly now.

If you want to chat on Skype, my handle is the same as my username on GitHub.
