### ISSUE TITLE
Add method to return string for direct URL to re-prompt anonymous users with opt-in

### ISSUE THREAD

**Issue by cliffordp** [Freemius/wordpress-sdk#42]
I want my wp-admin settings page to have an `href`/link/button like "Changed your mind? Connect to Freemius!" only displayed to users who clicked "Skip" (by accident, on purpose, or because they later learned more about the benefits of opting-in).

Possibly related to #22

**Comment by danieliser** [comment]
:+1: This handles what I was after in #22.
