### ISSUE TITLE
Undefined index: REQUEST_METHOD in config.php:166

### ISSUE THREAD

**Issue by mircobabini** [Freemius/wordpress-sdk#452]
# 🐞 bug report

**Behavior**:
 -  `What is the issue? (*)`
Undefined index notice in debug.log. PHP Notice:  Undefined index: REQUEST_METHOD in ... [freemius/config.php on line 166](https://github.com/Freemius/wordpress-sdk/blob/master/config.php#L166). This happens when running wordpress by cli/wp-cron.php. Example: `$ php wp-cron.php`
 -  `What is the expected behavior?`
No notice, please :)

**Versions**: (*)
 -  `Freemius SDK Version:`  latest
 -  `WordPress Version:`  latest
 -  `PHP Version:`  any

**Plugin / Theme**: (*)
 -  `Name:`  ininfluent
 -  `Slug:`  ininfluent
 -  `Freemius ID:`  ininfluent

**Additional Information**:
 -  `Browser Type: (*)` ininfluent
 -  `Browser Version: (*)` ininfluent
 -  `OS: (*)` ininfluent
 -  `Stack Traces:`

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by timnolte** [comment]
This is blowing up the WordPress logs on a lot of sites because I use the WP-CLI via a server-side cron job to run the WP Cron.

**Comment by andreuka** [comment]
same issue here still.

**Comment by vovafeldman** [comment]
Closed in https://github.com/Freemius/wordpress-sdk/pull/608 (will be released in the upcoming version).
