### ISSUE TITLE
Shouldn't package.json have the Version listed as 2.4.1 instead of 2.4.0

### ISSUE THREAD

**Issue by ggedde** [Freemius/wordpress-sdk#464]
# 🐞 bug report

**Behavior**:
 -  `What is the issue? (*)`
package.json has the version listed as 2.4.0, but it should now be 2.4.1

**Versions**: (*)
 -  `Freemius SDK Version:` 2.4.1

**Comment by vovafeldman** [comment]
Thanks for the catch, @ggedde! Closed https://github.com/Freemius/wordpress-sdk/commit/d0a73a90e25a2b1b51a9dff3b5e8bd38505b7bb4
