### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by Yulinn233** [Freemius/wordpress-sdk#469]
Hello, I found a little problem with the Chinese translation of Freemius/wordpress-sdk 

1. "&#x27a4 ;" and "&#x2190 ;" translate as full-width symbols ";" This will cause the symbols in the plug-in upgrade menu to be displayed unusual;
2. "%s to access version %s security & feature updates, and support."
Not translated correctly

I tried to go to https://www.transifex.com/freemius/wordpress-sdk/ to correct the translation, but I could not join the Chinese (China) team

**Comment by vovafeldman** [comment]
Hi @Yulinn233, I just added you as a translator to our Transifex translation project so you can fix the translation you mentioned. Can you please explain #1? I'm not sure I understand what you mean.

**Comment by Yulinn233** [comment]
It is the full-width symbols (punctuation marks in the Chinese environment) used in the translated strings, which cause some wrong words to appear. For example, "→" this symbol will display errors;
  The English that I use Google Translate may not be very clear, but I’m in the translation project, I will handle it myself. Thank you
