### ISSUE TITLE
Seeing FOUC for v2.4.2 opt-in screen

### ISSUE THREAD

**Issue by dgwyer** [Freemius/wordpress-sdk#479]
# 🐞 bug report

**Behavior**:
 -  Is anyone else seeing quite a prominent FOUC (flash of unstlyed content) when the opt-in page is refreshed on SDK v2.4.2? Note: The screenshot below shows the unstyled content that is visible for a split-second. But every time the page is refreshed the unstyled content is clearly visible.

<img width="509" alt="fouc" src="https://user-images.githubusercontent.com/1482075/107942140-bea75100-6f82-11eb-859f-f24be4280a55.png">

I tested the previous SDK version (2.4.1) and while it looks like there is still some FOUC going on it's almost imperceptible compared with v2.4.2.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.4.2
 -  `WordPress Version:` 5.6.1
 -  `PHP Version:` 7.3.1

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 88.0.4324.150 (Official Build) (64-bit)`
 -  `OS: Windows 10`

**Comment by vovafeldman** [comment]
Closed 5641d57f2eefded43a7a439adfbee636dcdfa2e1, will be released with the upcoming version.
