### ISSUE TITLE
MALICIOUS CODE PATTERN DETECTED by Jetpack

### ISSUE THREAD

**Issue by Seema-SSLZEN** [Freemius/wordpress-sdk#500]
The client is getting the below error message when trying to install the SSL Zen plugin on their WordPress.

![image](https://user-images.githubusercontent.com/74591092/120159000-5b2fef00-c212-11eb-9de7-022deaa2eb16.png)

**According to Freemius expert @vovafeldman, this can be the cause of the issue:**
Theme Check is flagging base64 methods with a warning, since historically, different encodings were used to add malicious code. Since we use base64 for storing sensitive data in the DB and for the API communication signature, we were recommended by a wp.org rep to use that hack-y solution to overcome Theme Check warning. There’s actually a documentation about that in the code. 

Kindly help in fixing this issue asap.

**Comment by bradvin** [comment]
A client of mine also reported the same problem. I understand it might be a false positive, but it should still be addressed as people trust Jetpack and I am worried this alert will give them a bad impression

**Comment by vovafeldman** [comment]
Jetpack whitelisted this false-positive.
