### ISSUE TITLE
Notice - wpmu_new_blog deprecated

### ISSUE THREAD

**Issue by tserofcj** [Freemius/wordpress-sdk#507]
Hello,
You are using a deprecated hook [wpmu_new_blog](https://developer.wordpress.org/reference/hooks/wpmu_new_blog/) in /includes/class-freemius.php :
`add_action( 'wpmu_new_blog', array( $this, '_after_new_blog_callback' ), 10, 6 );`
We recently updated our wordpress version, and now we get this notice every time we add a new site within the multisite network.
Could you use wp_insert_site or wp_insert_site instead ?

Best regards,

**Comment by asadowski10** [comment]
Deprecated hook since WP 5.1

**Comment by vovafeldman** [comment]
Fixed in https://github.com/Freemius/wordpress-sdk/pull/447

Will be released with the upcoming version.
