### ISSUE TITLE
Error: Unknown format specifier "�" /freemius/templates/forms/deactivation/retry-skip.php:23

### ISSUE THREAD

**Issue by presswizards** [Freemius/wordpress-sdk#510]
# 🐞 bug report

**Behavior**:
 -  `What is the issue? (*)`
 
Someone using our plugin Featured Images in RSS which uses Freemius SDK 2.4.2 reported the following error after updating to PHP 8.0, it appears in the footer of the Installed Plugins page:

Error: Unknown format specifier "�" in /var/www/user/data/www/hisdomain.co/wp-content/plugins/featured-images-for-rss-feeds/includes/freemius/templates/forms/deactivation/retry-skip.php:23 Stack trace: #0 /var/www/user/data/www/hisdomain.co/wp-content/plugins/featured-images-for-rss-feeds/includes/freemius/templates/forms/deactivation/retry-skip.php(23): sprintf('\xD0\x92\xD0\xBE\xD0\xB7\xD0\xBC\xD0\xBE\xD0\xB6\xD0\xBD\xD0...', '<a href='https:...') #1 /var/www/user/data/www/hisdomain.co/wp-content/plugins/featured-images-for-rss-feeds/includes/freemius/includes/fs-core-functions.php(57): require('/var/www/u09986...') #2 /var/www/user/data/www/hisdomain.co/wp-content/plugins/featured-images-for-rss-feeds/includes/freemius/includes/class-freemius.php(2619): fs_get_template('forms/deactivat...', Array) #3 /var/www/u0998617/data/www/hisdomain.co/wp-content/plugins/featured-images-for-rss-feeds/includes/freemius/includes/class-freemius.php(2498): Freemius->_get_uninstall_reasons('long-term') #4 /var/www/user/data/www/hisdomain.co/wp-includes/class-wp-hook.php(292): Freemius->_add_deactivation_feedback_dialog_box('') #5 /var/www/user/data/www/hisdomain.co/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #6 /var/www/user/data/www/hisdomain.co/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #7 /var/www/user/data/www/hisdomain.co/wp-admin/admin-footer.php(78): do_action('admin_footer', '') #8 /var/www/user/data/www/strategycon.ru/wp-admin/plugins.php(782): require_once('/var/www/user...') #9 {main} thrown in /var/www/user/data/www/hisdomain.co/wp-content/plugins/featured-images-for-rss-feeds/includes/freemius/templates/forms/deactivation/retry-skip.php on line 23

**Versions**: (*)
 -  `Freemius SDK Version:`  2.4.2
 -  `WordPress Version:`  5.8
 -  `PHP Version:`  8.0

**Plugin / Theme**: (*)
 -  `Name:` Featured Images in RSS
 -  `Slug:` featured-images-for-rss-feeds
 -  `Freemius ID:` 195

**Additional Information**:
 -  `Browser Type: (*)` Chrome
 -  `Browser Version: (*)` 91
 -  `OS: (*)` Windows
 -  `Stack Traces:` Above.

**Comment by bradvin** [comment]
Also got the same issue logged by a user of FooBox : https://wordpress.org/support/topic/php80-problem


Freemius SDK Version: 2.4.2
WordPress Version: 5.8
PHP Version: 8.0
Name: FooBox Image Lightbox
Slug: foobox-image-lightbox
Freemius ID: 374

**Comment by vovafeldman** [comment]
This is related to the Russian translation and was already fixed in the `develop` branch.

**Comment by niklasp** [comment]
So @vovafeldman are you telling us to use "develop"? is it safe to use in production. There is no update since Aug 23?

**Comment by vovafeldman** [comment]
@niklasp you can try [2.5.0-rc.1](https://github.com/Freemius/wordpress-sdk/releases/tag/2.5.0-rc.1) or alternatively, just copy the [languages folder](https://github.com/Freemius/wordpress-sdk/tree/2.5.0-rc.1/languages).
