### ISSUE TITLE
Class 'Freemius_Exception' not found 

### ISSUE THREAD

**Issue by Mte90** [Freemius/wordpress-sdk#53]
```
PHP Fatal error:  Class 'Freemius_Exception' not found in /htdocs/wp-content/plugins/xxxxxxxxxxxx/includes/freemius/includes/class-freemius.php on line 2068
```
I get that error when i enable freemius

**Comment by vovafeldman** [comment]
This error is relevant for all versions :) No one just ever triggered it. Thanks for finding it and we'll fix it for the next version.

Btw. Seems like you forgot to configure the 'id' parameter in the init SDK call.

**Comment by Mte90** [comment]
Yes I saw that in the code for the id, I saw that locally freemius works also with fake id so I tried to insert an empty value.
