### ISSUE TITLE
use remote plugin icon on opt-in please

### ISSUE THREAD

**Issue by Tobias-Conrad** [Freemius/wordpress-sdk#549]
See screenshot please
https://somup.com/c3elbMTA7j

a solution could be to load the plugin icon from freemius.
That would save a lot of time, so devs not to copy paste icon into sdk folder on sdk update...

**Comment by swashata** [comment]
Hello @Tobias-Conrad,

Thank you very much for the detailed explanation. I really appreciate it. It looks like you need a way to change the `plugin_icon` programmatically.

Our SDK has a way to do that. Please see the [documentation here](https://freemius.com/help/documentation/wordpress-sdk/opt-in-message/#icon_customization). The gist is

```php
function my_fs_custom_icon() {
    return dirname( __FILE__ ) . '/local/path/to/your/icon.{png|jpg|gif|svg}';
}
 
my_fs()->add_filter( 'plugin_icon' , 'my_fs_custom_icon' );
```

Please feel free to close this issue if you find it satisfactory.

**Comment by swashata** [comment]
Closing due to no activities.
