### ISSUE TITLE
Problem to downgrade plan

### ISSUE THREAD

**Issue by nicolas92** [Freemius/wordpress-sdk#55]
Hello, I have a little problem on the plan page.
There are two plans "free version" and "premium version", I test the premium version, but when I want to go back to the free version, I click the "Downgrade" button and nothing happens, it's normal ?

Thank you very much :)

**Comment by vovafeldman** [comment]
@nicolas92 sorry for the late response. Are you talking about the pricing or the account page?

**Comment by nicolas92** [comment]
Hello, the problem has been solved, thank anyway :)

**Comment by DeoThemes** [comment]
I'm having the same issue. Any solution for this?
