### ISSUE TITLE
Not compatible with PHP 8.1

### ISSUE THREAD

**Issue by princeahmed** [Freemius/wordpress-sdk#568]
Many websites started using PHP 8.1. And if they installed the plugin they couldn't use the plugin as they are getting too many errors with the freemius SDK.

Can you please tell me how can I get rid of this?

![image](https://user-images.githubusercontent.com/36558734/177530666-fc927fc0-8650-4cf2-975d-1609acf74c73.png)

**Comment by vovafeldman** [comment]
Thanks for raising the awareness, @princeahmed. A fix was already addressed a while ago in the `develop` branch (#537).

And we also released [2.4.4](https://github.com/Freemius/wordpress-sdk/tree/2.4.4) yesterday as an official patch of 2.4.3, which mutes all of those deprecations.
