### ISSUE TITLE
RTL Compatibility

### ISSUE THREAD

**Issue by kjohnson** [Freemius/wordpress-sdk#57]
The Freemius Opt-In box is not RTL Compatible.

Custom Submitted Screenshot:
![freemius_ninja_forms_rtl](https://cloud.githubusercontent.com/assets/10858303/15482197/4948b75c-20fc-11e6-8c0a-700402672b2a.png)

**Comment by vovafeldman** [comment]
Thanks for reporting @kjohnson. We actually did spend time to support RTL. Maybe we messed something on that angle during the way. We'll take a look and try to fix it for the next SDK release.

**Comment by kjohnson** [comment]
Additional comments from the customer:

> In order to replicate the problem, you have to have the Arabic Wordpress core from here <https://ar.wordpress.org/>, with the latest version of Ninja Forms. I found the problem in 3 new instals of Wordpress and Ninja Forms, even without installing any other plugins.

**Comment by fajardoleo** [comment]
Hi @kjohnson, I downloaded the Arabic version of WordPress (4.5.2) from this page https://ar.wordpress.org/ and installed it locally. I also installed the latest version of Ninja Forms (2.9.47).

I got a different result, please see the image below.

![wp4 5 2_ar](https://cloud.githubusercontent.com/assets/16242034/15943815/597ede2a-2ebd-11e6-87b1-5591af7d9413.png)

Could you please clarify if that output is good or bad? Please also tell us what else did you do, what versions of WordPress did you test, etc. Thanks.
