### ISSUE TITLE
PHP 8.1 Deprecated notices

### ISSUE THREAD

**Issue by alanef** [Freemius/wordpress-sdk#577]
# 🐞 bug report

I know a deprecation notice is not a bug but it impacts a) developer testing b) users that panic

**Behavior**:
 -  Deprecated: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/wp-includes/Requests/Cookie/Jar.php on line 63

**Versions**: (*)
 -  `Freemius SDK Version:` 2.4.5
 -  `WordPress Version:` 6.0.1
 -  `PHP Version:` 8.1

**Plugin / Theme**: (*)
 -  `Name:` Display Eventbrite
 -  `Slug:` widget-for-eventbrite-api
 -  `Freemius ID:` 1330

**Additional Information**:
 -  `Browser Type: (*)` Any
 -  `Browser Version: (*)` Any
 -  `OS: (*)` Any
 -  `Stack Traces:`
 
 

# | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0010 | 445480 | {main}( ) | .../index.php:0
2 | 0.0016 | 484688 | require_once( '/var/www/html/wp-admin/admin.php ) | .../index.php:10
3 | 0.8785 | 63173600 | require( '/var/www/html/wp-admin/menu.php ) | .../admin.php:158
4 | 0.8895 | 63271320 | require_once( '/var/www/html/wp-admin/includes/menu.php ) | .../menu.php:394
5 | 0.8918 | 63273024 | do_action( $hook_name = 'admin_menu', ...$arg = variadic('') ) | .../menu.php:155
6 | 0.8918 | 63273400 | WP_Hook->do_action( $args = [0 => ''] ) | .../plugin.php:476
7 | 0.8918 | 63273400 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | .../class-wp-hook.php:331
8 | 0.9070 | 63349840 | Freemius->_prepare_admin_menu( '' ) | .../class-wp-hook.php:307
9 | 0.9071 | 63354312 | Freemius->add_submenu_items( ) | .../class-freemius.php:17943
10 | 0.9073 | 63359176 | Freemius->is_whitelabeled( $ignore_data_debug_mode = ???, $blog_id = ??? ) | .../class-freemius.php:18332
11 | 0.9073 | 63359872 | Freemius->get_updated_account_addons( ) | .../class-freemius.php:12465
12 | 0.9125 | 63881896 | Freemius->fetch_valid_user_licenses( ) | .../class-freemius.php:19493
13 | 0.9126 | 63884032 | FS_Api->get( $path = '/licenses.json?type=active', $flush = ???, $expiration = ??? ) | .../class-freemius.php:19464
14 | 0.9127 | 63887584 | FS_Api->call( $path = '/licenses.json?type=active', $method = ???, $params = ??? ) | .../class-fs-api.php:275
15 | 0.9127 | 63887584 | FS_Api->_call( $path = '/licenses.json?type=active', $method = 'GET', $params = [], $retry = ??? ) | .../class-fs-api.php:241
16 | 0.9128 | 63891072 | Freemius_Api_Base->Api( $pPath = '/licenses.json?type=active&sdk_version=2.4.5', $pMethod = 'GET', $pParams = [] ) | .../class-fs-api.php:201
17 | 0.9128 | 63891168 | Freemius_Api_Base->_Api( $pPath = '/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $pMethod = 'GET', $pParams = [] ) | .../FreemiusBase.php:157
18 | 0.9128 | 63891168 | Freemius_Api_WordPress->MakeRequest( $pCanonizedPath = '/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $pMethod = 'GET', $pParams = [], $pWPRemoteArgs = ??? ) | .../FreemiusBase.php:137
19 | 0.9128 | 63892064 | Freemius_Api_WordPress::MakeStaticRequest( $pCanonizedPath = '/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $pMethod = 'GET', $pParams = [], $pWPRemoteArgs = NULL, $pIsSandbox = FALSE, $pBeforeExecutionFunction = [0 => class Freemius_Api_WordPress { protected $_id = '590207'; protected $_public = 'pxxxxxxxxxxxxxx7634d078505fbe5bfaf'; protected $_secret = 'sk_xxxxxxxxxxxxxxxxxxx1AZUvwYp=5>'; protected $_scope = 'user'; protected $_isSandbox = FALSE }, 1 => 'SignRequest'] ) | .../FreemiusWordPress.php:523
20 | 0.9130 | 63895024 | Freemius_Api_WordPress::ExecuteRequest( $pUrl = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $pWPRemoteArgs = ['method' => 'GET', 'connect_timeout' => 10, 'timeout' => 60, 'follow_redirects' => TRUE, 'redirection' => 5, 'user-agent' => 'Freemius/WordPress-SDK/1.0.4; http://localhost:8100', 'blocking' => TRUE, 'headers' => ['Expect' => '', 'Date' => 'Wed, 17 Aug 2022 09:27:57 +0000', 'Authorization' => 'FS 590207:xxxxxxxxxxxxxxxxxxxxxxxe5bfaf:NmIyMjYyNGFkZTBmYThmMDUxMmNlOWUzNjcwMGM1YTcwMmY3OGEyMjRkOTg2YzAxYWE0MjEyNGZiZmFkMjA2ZQ'], 'sslverify' => FALSE] ) | .../FreemiusWordPress.php:420
21 | 0.9130 | 63895024 | wp_remote_request( $url = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $args = ['method' => 'GET', 'connect_timeout' => 10, 'timeout' => 60, 'follow_redirects' => TRUE, 'redirection' => 5, 'user-agent' => 'Freemius/WordPress-SDK/1.0.4; http://localhost:8100', 'blocking' => TRUE, 'headers' => ['Expect' => '', 'Date' => 'Wed, 17 Aug 2022 09:27:57 +0000', 'Authorization' => 'FS 590207:xxxxxxxxxxxxxxxxf:NmIyMjYyNGFkZTBmYThmMDUxMmNlOWUzNjcwMGM1YTcwMmY3OGEyMjRkOTg2YzAxYWE0MjEyNGZiZmFkMjA2ZQ'], 'sslverify' => FALSE] ) | .../FreemiusWordPress.php:310
22 | 0.9130 | 63895472 | WP_Http->request( $url = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $args = ['method' => 'GET', 'connect_timeout' => 10, 'timeout' => 60, 'follow_redirects' => TRUE, 'redirection' => 5, 'user-agent' => 'Freemius/WordPress-SDK/1.0.4; http://localhost:8100', 'blocking' => TRUE, 'headers' => ['Expect' => '', 'Date' => 'Wed, 17 Aug 2022 09:27:57 +0000', 'Authorization' => 'FS 590207:xxxxxxxxxxxxxxxxx8505fbe5bfaf:NmIyMjYyNGFkZTBmYThmMDUxMmNlOWUzNjcwMGM1YTcwMmY3OGEyMjRkOTg2YzAxYWE0MjEyNGZiZmFkMjA2ZQ'], 'sslverify' => FALSE] ) | .../http.php:145
23 | 0.9132 | 63900904 | Requests::request( $url = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $headers = ['Expect' => '', 'Date' => 'Wed, 17 Aug 2022 09:27:57 +0000', 'Authorization' => 'FS 590207:xxxxxxxxxxxxxxxxxxxxx5bfaf:NmIyMjYyNGFkZTBmYThmMDUxMmNlOWUzNjcwMGM1YTcwMmY3OGEyMjRkOTg2YzAxYWE0MjEyNGZiZmFkMjA2ZQ'], $data = NULL, $type = 'GET', $options = ['timeout' => 60, 'useragent' => 'Freemius/WordPress-SDK/1.0.4; http://localhost:8100', 'blocking' => TRUE, 'hooks' => class WP_HTTP_Requests_Hooks { protected $hooks = [...]; protected $url = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5'; protected $request = [...] }, 'redirects' => 5, 'verify' => FALSE, 'verifyname' => FALSE] ) | .../class-wp-http.php:394
24 | 0.9132 | 63902400 | Requests::set_defaults( $url = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5', $headers = ['Expect' => '', 'Date' => 'Wed, 17 Aug 2022 09:27:57 +0000', 'Authorization' => 'FS 590207:xxxxxxxxxxxxxxxxxxxxxxxxxxf:NmIyMjYyNGFkZTBmYThmMDUxMmNlOWUzNjcwMGM1YTcwMmY3OGEyMjRkOTg2YzAxYWE0MjEyNGZiZmFkMjA2ZQ'], $data = NULL, $type = 'GET', $options = ['timeout' => 60, 'connect_timeout' => 10, 'useragent' => 'Freemius/WordPress-SDK/1.0.4; http://localhost:8100', 'protocol_version' => 1.1, 'redirected' => 0, 'redirects' => 5, 'follow_redirects' => TRUE, 'blocking' => TRUE, 'type' => 'GET', 'filename' => FALSE, 'auth' => FALSE, 'proxy' => FALSE, 'cookies' => FALSE, 'max_bytes' => FALSE, 'idn' => TRUE, 'hooks' => class WP_HTTP_Requests_Hooks { protected $hooks = [...]; protected $url = 'https://api.freemius.com/v1/users/590207/licenses.json?type=active&sdk_version=2.4.5'; protected $request = [...] }, 'transport' => NULL, 'verify' => FALSE, 'verifyname' => FALSE] ) | .../class-requests.php:365
25 | 0.9132 | 63902848 | Requests::autoloader( $class = 'Requests_Cookie_Jar' ) | .../class-requests.php:591
26 | 0.9136 | 63917032 | require_once( '/var/www/html/wp-includes/Requests/Cookie/Jar.php )

----

**Comment by vovafeldman** [comment]
@alanef this is a core file unrelated to the Freemius WordPress SDK.

**Comment by alanef** [comment]
Why was this closed. This is an issue with Freemius interaction with Core not core itself

**Comment by vovafeldman** [comment]
@alanef from what it looks like `Requests_Cookie_Jar` is implementing `ArrayAccess`, which in newer PHP versions has a `bool` return type and therefore, is inconsistent with the implementation in core:
![image](https://user-images.githubusercontent.com/6830121/205488860-ce535bb3-48de-4b19-9fb9-165c9ccfbdf1.png)

How would you expect us to tackle it?

**Comment by alanef** [comment]
I don't know how you solve it, but is seems unique to the way  Freemius is
implementing add sub menu.  But I don't undesrtand the root cause, or why
it only seems to be an issue when Freemoius WP SDK is active


Alan Fuller

Fullworks

***@***.*** | fullworks.net
<http://fullworks.net/?pk_campaign=emailsig&pk_kwd=emailtextlink&utm_source=emailsig&utm_medium=email&utm_content=sigtextlink&utm_campaign=email>

Fullworks Digital Ltd is a company registered in England and Wales.
Registered number: 07720957. Registered office: Station House, Station
Approach, East Horsley, Surrey KT24 6QX. Email confidentiality notice This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system.
