### ISSUE TITLE
issue for non-admins

### ISSUE THREAD

**Issue by selu91** [Freemius/wordpress-sdk#58]
Hello,

I'm using the next configuration for the freemius: 

```
$im_fs = fs_dynamic_init( array(
			'id'                => '',
			'slug'              => 'intergeo-maps',
			'public_key'        => '',
			'is_premium'        => false,
			'has_addons'        => false,
			'has_paid_plans'    => false,
			'anonymous_mode'    => true,
			'menu'              => array(
				'slug'       => 'intergeo',
				'account'    => false,
				'support'    => false,
				'parent'     => array(
					'slug' => 'upload.php',
				),
			),
		) );
```

If i log in with a non-admin account, simple subscriber, and i get some errors on the admin screen: 

> Warning: Invalid argument supplied for foreach() in D:\Dezvoltare\php\wordpress\wp-content\plugins\intergeo-maps\freemius\includes\class-freemius.php on line <i>6339</i>

and also: 

>  Warning: Invalid argument supplied for foreach() in D:\Dezvoltare\php\wordpress\wp-admin\includes\plugin.php on line 1537

Im using the latest wordpress of 4.5.2 and the latest freemius SDK.

I've tried to add this : 
  `if (empty($top_level_menu)) return;` 

here https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L6338 

But i still get the second error.

Any clue what it could be  ?

**Comment by vovafeldman** [comment]
Thanks for reporting @selu91! Will be fixed in the upcoming release.
