### ISSUE TITLE
update wp_option fs_accounts spam fills up my database server mysql bin log files in a few days

### ISSUE THREAD

**Issue by minerva-atrix** [Freemius/wordpress-sdk#587]
# 🐞 bug report

**Behavior**:
update wp_option fs_accounts spam fills up my database server mysql bin log files in a few days, we're talking 50+ gigabytes and it fills up the entire servers hard drive until it breaks.  This didn't used to the be an issue yet we don't recall changing anything that would affect it.  I tried doing a hook to make it skip updates to fs_accounts but then plugins stop working.  There's no reason this needs to update 15+ times per backend page load but it does.  Several of our plugins use it and each one can call the update query multiple times.

**Versions**: (*)
 -  `Freemius SDK Version:` Whatever several diff plugins our site uses, uses
 -  `WordPress Version:` 6.01
 -  `PHP Version:` 7.4

**Additional Information**:
 -  `Browser Type: (*)` Any
 -  `Browser Version: (*)` Any
 -  `OS: (*)` ANy
 -  `Stack Traces:` You can make one with the code profiler.

**Comment by vovafeldman** [comment]
Duplicate https://github.com/Freemius/wordpress-sdk/issues/574

We've updated the [deubgging documentation](https://freemius.com/help/documentation/wordpress-sdk/debugging/) with a new warning:

![image](https://user-images.githubusercontent.com/6830121/198873358-9dd9569e-a571-4f99-8041-4853e39dd74d.png)

We'll also consider introducing a similar warning in the SDK itself. Thanks!
