### ISSUE TITLE
wp-config.php without security tokens fatal error on activation

### ISSUE THREAD

**Issue by SteveJonesDev** [Freemius/wordpress-sdk#589]
# 🐞 bug report

**Behavior**:
 -  `What is the issue? (*)`
Plugin can't be activated on very old sites. Sites created prior to WordPress 2.6 don't have the security tokens in wp-config.php, and Freemius throws fatals if those aren't present. Any site with professional maintenance has probably had the config file upgraded at some point, but it's not done as part of the upgrade process, so it's not a guarantee. So it's possible to have a site running a current version or WordPress without security tokens.

 -  `What is the expected behavior?`
Possibly have Freemius fail more gracefully without out causing fatal errors.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.4.3
 -  `WordPress Version:` 6.1
 -  `PHP Version:` 8.1

**Plugin / Theme**: (*)
 -  `Name:` Accessibility Checker
 -  `Slug:` accessibility-checker
 -  `Freemius ID:` 7322

**Additional Information**:
 -  `Browser Type: (*)` All
 -  `Browser Version: (*)` All
 -  `OS: (*)` All
 -  `Stack Traces:`

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vovafeldman** [comment]
Thanks, @SteveJonesDev. The issue is already resolved in the `develop` branch and will be included in the upcoming SDK release.
