### ISSUE TITLE
Wrong renewal notice on order review

### ISSUE THREAD

**Issue by intoxstudio** [Freemius/wordpress-sdk#59]
When testing monthly payments (in Sandbox mode), I got this message when reviewing order:

<img width="595" alt="udklip" src="https://cloud.githubusercontent.com/assets/1677777/15790455/3679cd9a-2986-11e6-83a7-7c6d33a9746f.PNG">

Point 3 does not display the value correctly, and it should state monthly renewal payments instead of annual.

When testing annual payments the same way, the message is:

<img width="587" alt="udklip2" src="https://cloud.githubusercontent.com/assets/1677777/15790983/9bef9a94-2989-11e6-8b19-a0db008ede1d.PNG">

Point 3 does not display the value correctly.

SDK version 1.1.8.1.

**Comment by vovafeldman** [comment]
Closed #59 (resolved)
