### ISSUE TITLE
Leverage the WordPress.org plugins API to fetch the URL of the plugin's icon.

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#67]
Currently `/templates/plugin-icon.php` tries to fetch 128x128 & 256x256 icons from the SVN using HTTP, and stores the 1st version that returns a real image. Apparently, it's possible to fetch the icon from the plugins API by adding `icons` as one of the `fields` params in the querystring:

`http://api.wordpress.org/plugins/info/1.0/{slug}.json?fields=banners,icons`

**Comment by bfintal** [comment]
You can also use this for a smaller result size:

	$payload = array(
		'action' => 'plugin_information',
		'request' => serialize( (object) array(
			'slug' => 'page-builder-sandwich',
			'fields' => array(
				'tags' => false,
				'icons' => true,
				'sections' => false,
				'description' => false,
				'tested' => false,
				'requires' => false,
				'rating' => false,
				'downloaded' => false,
				'downloadlink' => false,
				'last_updated' => false,
				'homepage' => false,
				'tags' => false,
				'compatibility' => false,
				'ratings' => false,
				'added' => false,
				'donate_link' => false,
			),
		) ),
	);
	$body = wp_remote_post( 'http://api.wordpress.org/plugins/info/1.0/', array( 'body' => $payload ) );

	var_dump( unserialize( $body['body'] )->icons );
