### ISSUE TITLE
Loading image on VVV does not work

### ISSUE THREAD

**Issue by brianhogg** [Freemius/wordpress-sdk#7]
From https://github.com/Freemius/wordpress-sdk/issues/3 the instructions to load the plugin image does not work if the local development environment is not running on actual localhost.  In my VVV environment `$_SERVER['REMOTE_ADDR']` is `192.168.50.1` so this line in freemius/config.php will never be true:

```
	define( 'WP_FS__IS_LOCALHOST', ( substr( $_SERVER['REMOTE_ADDR'], 0, 4 ) == '127.' || $_SERVER['REMOTE_ADDR'] == '::1' ) );
```

and `WP_FS__IS_LOCALHOST` needs to be true for the icon to be downloaded locally in template/plugin-icon.php

**Comment by brianhogg** [comment]
Also if the icon is not downloaded the HTML generated has the plugin's img src as a broken image rather than the plugin default image

**Comment by fs-contributor** [comment]
Added `WP_FS__LOCALHOST_IP` constant to `config.php` for local environments with custom local IP + if from some reason the fails to fetch the plugin's icon, fall backs to generic local icon.

Ref: [f8df74e] [22d35aa]
