### ISSUE TITLE
[Freemius SDK 2.7.1] PHP Fatal error:  Uncaught Error: Call to a member function is_expired() on bool using 

### ISSUE THREAD

**Issue by codex-m** [Freemius/wordpress-sdk#707]
# 🐞 bug report

**Behavior**:
 -  `What is the issue? (*)`
  While testing  Freemius SDK 2.7.1 - we noticed there is a new fatal error when user activates the product and optin to Freemius (by clicking "Allow and Continue"). I think this issue is critical because even free user ignores this (by refreshing or navigating away from the Account page). The same error occurs again after user purchase (right after checkout) when user is redirected back to Account. This can confuse new customers and even give them poor user experience.

_This is not reproducible with Freemius SDK 2.7.0._

**Steps to reproduce**:

1. Create blank /fresh installed WordPress site with a user email not yet registered or associated with Freemius.
2. Activate a Freemius powered plugin using SDK 2.7.1 (e.g. the[ latest Prime Mover FREE 1.9.9-beta6](https://codexonics.com/prime-mover/beta/prime-mover-free.1.9.9-beta6.zip))
3. In the opt-in dialog click "_Allow and Continue_" to optin.
4. While it waits the email to be received - click on "Account" (this is accessible in _Prime Mover -> Account_).

**Actual result**: User sees a critical error on account page. It is not accessible. 

 -  `What is the expected behavior?`
  No fatal error - user can still see the Account page.

**Versions**: (*)
 -  `Freemius SDK Version:`  2.7.1
 -  `WordPress Version:` 6.5.2
 -  `PHP Version:`  7.4 (and also reproducible even with PHP 8.1)

**Plugin / Theme**: (*)
 -  `Name:`  Prime Mover
 -  `Slug:`  prime-mover
 -  `Freemius ID:`  3826

**Additional Information**:
 -  `Browser Type: (*)` Any
 -  `Browser Version: (*)` n/a
 -  `OS: (*)` Linux and also reproducible with Windows using Local by Flywheel
 -  `Stack Traces:`
 `23-Apr-2024 13:18:59 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_expired() on bool in /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php:21352`

`Stack trace:`
`#0 /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php(21093): Freemius->_sync_plugin_license()`
`#1 /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php(6755): Freemius->_sync_license()`
`#2 /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php(6667): Freemius->_sync_cron_method()`
`#3 /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php(6737): Freemius->execute_cron()`
`#4 /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php(6720): Freemius->_sync_cron()`
`#5 /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php(23410) in /home/emerson/sourcecode/testplatform/wp-content/plugins/prime-mover/freemius/includes/class-freemius.php on line 21352`

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by swashata** [comment]
Thank you for reporting. @DanieleAlessandra would be working on it.

**Comment by DanieleAlessandra** [comment]
This should solve the issue
https://github.com/Freemius/wordpress-sdk/pull/708

Please give me a feedback
