### ISSUE TITLE
Free version of plugin dissappears when updating

### ISSUE THREAD

**Issue by intoxstudio** [Freemius/wordpress-sdk#71]
Related: #70

If a user has both a wp.org/free and a freemius version of a plugin, and he updates the free version, it dissappears (and the freemius version is updated successfully).

Reproduce issue:
1. have wp.org and freemius versions on the site, leave wp.org version inactive
2. push update to freemius and wp.org
3. go to plugins screen and update the free version (there should be no update notice on freemius version)
4. wp.org version dissappears and freemius version is updated

SDK version 1.1.9.

**Comment by vovafeldman** [comment]
Resolved at 98423d662057c84d335c989d8996955169cb758b

Was happening due to the cached value of `$this->_storage->plugin_main_file` and the registered uninstall hook.
