### ISSUE TITLE
Activation fails if the plugin's dir is outside of the WP plugins folder and configured with symlinks

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#8]
`debug_backtrace()` returns the real path of the stack calls, therefore if the plugin's folder is outside of `WP_PLUGIN_DIR`, the function `_find_caller_plugin_file()` can't find the correct calling plugin file. We need to map `debug_backtrace()`'s paths based on symlinks (if exist).

**Comment by fs-contributor** [comment]
Suggested alternative:
https://gist.github.com/fs-contributor/24b0440bdb0dfc8c69aa

Still needs some testing.

**Comment by fs-contributor** [comment]
3rd attempt https://gist.github.com/fs-contributor/bd2ce60c4ce222f65c27
