### ISSUE TITLE
Make Freemius Content Mobile Friendly

### ISSUE THREAD

**Issue by steveush** [Freemius/wordpress-sdk#88]
Hi,

We noticed when implementing freemius in one of our plugins that the content served by clicking on the _Account_, _Contact Us_ or _Upgrade_ links is not mobile friendly. This is quite important to us as some partner programs will reject the plugin outright if the admin is not mobile friendly.

Could this please be fixed?

Thanks

**Comment by vovafeldman** [comment]
@steveush forgot to close this one, the SDK's templates are now fully responsive.
