### ISSUE TITLE
Incompatibility with Query Monitor

### ISSUE THREAD

**Issue by intoxstudio** [Freemius/wordpress-sdk#90]
When a plugin with Freemius and Query Monitor are both activated, and Freemius DEBUG is ON, the following error occurs on every page:

Notice: Undefined index: file in ...\lib\freemius\includes\fs-essential-functions.php on line 265

A complete html error page seems to be appended to all public pages, which in my case "defaces" the site. It contains this message:

Freemius SDK couldn't find the plugin's main file. Please contact sdk@freemius.com with the current error.

SDK version 1.2.0.

**Comment by vovafeldman** [comment]
@intoxstudio do you know if you had **Debug Bar** active as well during the test?

**Comment by intoxstudio** [comment]
@vovafeldman Debug Bar was not active. However, the latest update of Query Monitor (2.13.1) seems to have resolved the issue.

**Comment by vovafeldman** [comment]
@intoxstudio I don't think it's related to Query Monitor (or Debug Bar). And we are pretty sure that we've found the bug - https://github.com/Freemius/wordpress-sdk/commit/21d1c8e0865fc476c8f65d0d1bdbdb7b42c150a0

Could you please try using the `develop` branch and see if it happens with the previous **Debug Bar** version?
